# SPDX-License-Identifier: MIT
# Copyright (c) 2023 University of Washington

DRV_DIR := $(shell git rev-parse --show-toplevel)
TARGET := exe.riscv
PLATFORM ?= ph
SIM_OPTIONS += --verbose 0
include $(DRV_DIR)/mk/riscv_common.mk
