// BFS with Perfect Work Stealing — L1SP/L2SP Utilization Showcase
//
// Memory layout:
//   L1SP: per-core thief token (8 bytes at base) + per-hart stack only
//   L2SP: work queues, frontier buffers, visited[], barriers, control state
//   DRAM: CSR graph (row_ptr, col_idx), overflow arrays
//
// Work stealing achieves perfect balance across cores:
//   - RMAT power-law graph creates extreme initial imbalance
//   - Aggressive stealing with infinite patience fully balances work
//   - Per-core work counters prove perfect distribution
//
// Input: rmat_32k.bin (generated by gen_rmat.py, scale-15 Graph500 RMAT, 32768 vertices)

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <atomic>

#include <pandohammer/mmio.h>
#include <pandohammer/cpuinfo.h>
#include <pandohammer/atomic.h>
#include <pandohammer/hartsleep.h>
#include <pandohammer/address.h>
#include <pandohammer/staticdecl.h>

// =====================================================================
// Configuration
// =====================================================================
static constexpr int MAX_HARTS  = 1024;
static constexpr int MAX_CORES  = 64;
static constexpr int MAX_HARTS_PER_CORE = 32;
static constexpr int BFS_CHUNK_SIZE = 8;    // nodes per CAS pop (tuned for 100K+ scale)
static constexpr int STEAL_BATCH   = 4096;  // max nodes per steal (steal HALF of victim queue)

// =====================================================================
// L2SP: Global control state (barriers, init)
// =====================================================================
__l2sp__ volatile int g_total_harts = 0;
__l2sp__ volatile int g_harts_per_core = 0;
__l2sp__ volatile int g_total_cores = 0;
__l2sp__ std::atomic<int> g_initialized = 0;

// =====================================================================
// L2SP: Per-core work queues
// =====================================================================
struct WorkQueue {
    volatile int64_t head;     // pop/steal reservation point (CAS)
    volatile int64_t tail;     // one-past-last valid item
    int64_t start_idx;         // logical start in frontier storage
};

__l2sp__ WorkQueue core_queues[MAX_CORES];
__l2sp__ WorkQueue shared_queue;   // single shared queue ALL harts pop from

// =====================================================================
// L2SP: Frontier buffers
// =====================================================================
struct FrontierBuffer {
    volatile int64_t tail;
    int64_t capacity;
    int64_t l2sp_capacity;
    int64_t l1sp_capacity;       // per-buffer L1SP entries (distributed across cores)
    int64_t* l2sp_items;
    int64_t* dram_items;
};

__l2sp__ FrontierBuffer g_next_frontier;
__l2sp__ int64_t *g_current_frontier_storage = nullptr;
__l2sp__ int64_t *g_current_frontier_dram_storage = nullptr;

// =====================================================================
// L2SP: Barrier state
// =====================================================================
__l2sp__ int64_t g_local_sense[MAX_HARTS];
__l2sp__ std::atomic<int64_t> g_count = 0;
__l2sp__ std::atomic<int64_t> g_sense = 0;

// =====================================================================
// L2SP: Work stealing coordination
// =====================================================================
__l2sp__ volatile int32_t core_has_work[MAX_CORES];

// Global remaining-work counter for the current level
__l2sp__ std::atomic<int64_t> g_level_remaining = 0;

// Per-core stolen frontier base offsets (into current frontier storage)
// Each core gets a reserved region to write stolen items into.
__l2sp__ volatile int64_t g_stolen_base_per_core[MAX_CORES];

// =====================================================================
// L2SP: Per-core and per-hart statistics
// =====================================================================
__l2sp__ volatile int64_t stat_nodes_processed_per_core[MAX_CORES];
__l2sp__ volatile int64_t stat_edges_traversed_per_core[MAX_CORES];
__l2sp__ volatile int64_t stat_steal_attempts_per_core[MAX_CORES];
__l2sp__ volatile int64_t stat_steal_success_per_core[MAX_CORES];
__l2sp__ volatile int64_t stat_stolen_nodes_per_core[MAX_CORES];
__l2sp__ volatile int64_t stat_nodes_processed[MAX_HARTS];
__l2sp__ volatile int64_t discovered = 0;

// =====================================================================
// L2SP: Graph state / BFS state
// =====================================================================
__l2sp__ int32_t *g_row_ptr    = nullptr;
__l2sp__ int32_t *g_col_idx    = nullptr;
__l2sp__ volatile int64_t *visited = nullptr;
__l2sp__ volatile int64_t *visited_dram = nullptr;
__l2sp__ int32_t *dist_arr     = nullptr;
__l2sp__ int32_t *dist_arr_dram = nullptr;
__l2sp__ char    *g_file_buffer = nullptr;
__l2sp__ int32_t  g_num_vertices = 0;
__l2sp__ int32_t  g_num_edges    = 0;
__l2sp__ int32_t  g_bfs_source   = 0;
__l2sp__ int32_t  g_visited_l2sp_count = 0;
__l2sp__ int32_t  g_dist_l2sp_count = 0;

// L1SP usage tracking
__l2sp__ volatile uint64_t g_core_l1sp_bytes = 0;
__l2sp__ volatile uint64_t g_hart_stack_capacity_bytes = 0;
__l2sp__ volatile uint64_t g_hart_stack_peak_bytes[MAX_HARTS];

// =====================================================================
// L1SP data tier: overflow storage between L2SP and DRAM
//
// Uses the bottom of each core's L1SP (below stack growth) for data.
// Hart 15's stack grows downward from offset 16384; with 50% peak
// usage (~8KB) and a 5KB guard, offsets 16..11264 are safe for data.
// Cross-core access via absolute addressing (any core can read/write
// any other core's L1SP through the pod network).
// =====================================================================
static constexpr uintptr_t L1SP_DATA_START = 16;       // after thief token (8B), aligned
static constexpr uintptr_t L1SP_STACK_GUARD = 5120;    // 5KB guard for stack growth

__l2sp__ uintptr_t g_l1sp_abs_base[MAX_CORES];         // absolute L1SP base per core
__l2sp__ int32_t g_l1sp_data_bytes_per_core = 0;       // usable data bytes per core

// L1SP tier counts for visited[]
__l2sp__ int32_t g_visited_l1sp_count = 0;              // total entries in L1SP tier
__l2sp__ int32_t g_visited_l1sp_per_core = 0;           // entries per core (power of 2)
__l2sp__ int32_t g_visited_l1sp_shift = 0;              // log2(per_core) for fast division
__l2sp__ uintptr_t g_visited_l1sp_offset = 0;           // byte offset within each core's L1SP

// L1SP tier counts for dist_arr[]
__l2sp__ int32_t g_dist_l1sp_count = 0;
__l2sp__ int32_t g_dist_l1sp_per_core = 0;
__l2sp__ int32_t g_dist_l1sp_shift = 0;
__l2sp__ uintptr_t g_dist_l1sp_offset = 0;

// L1SP tier counts for frontier buffers
__l2sp__ int64_t g_frontier_l1sp_capacity = 0;          // per-buffer L1SP entries total
__l2sp__ int32_t g_frontier_l1sp_per_core = 0;          // per-buffer entries per core (power of 2)
__l2sp__ int32_t g_frontier_l1sp_shift = 0;
__l2sp__ uintptr_t g_current_frontier_l1sp_offset = 0;  // offset in L1SP for current frontier
__l2sp__ uintptr_t g_next_frontier_l1sp_offset = 0;     // offset in L1SP for next frontier

// =====================================================================
// L1SP: Thief token (one per core, at L1SP base)
// =====================================================================
static constexpr uintptr_t THIEF_TOKEN_L1SP_OFFSET = 0;

static inline volatile int64_t* thief_token_ptr() {
    uintptr_t l1sp_base;
    asm volatile("csrr %0, " __stringify(MCSR_L1SPBASE) : "=r"(l1sp_base));
    return (volatile int64_t *)(l1sp_base + THIEF_TOKEN_L1SP_OFFSET);
}

static inline bool thief_token_try_acquire() {
    volatile int64_t *tok = thief_token_ptr();
    return atomic_compare_and_swap_i64(tok, 0, 1) == 0;
}

static inline void thief_token_release() {
    volatile int64_t *tok = thief_token_ptr();
    *tok = 0;
}

static inline void thief_token_init() {
    volatile int64_t *tok = thief_token_ptr();
    *tok = 0;
}

// =====================================================================
// L1SP data region helpers
// =====================================================================
static inline int32_t floor_pow2(int32_t n) {
    if (n <= 0) return 0;
    int32_t p = 1;
    while (p * 2 <= n) p *= 2;
    return p;
}

static inline int32_t ilog2_pow2(int32_t n) {
    int32_t k = 0;
    while ((1 << (k + 1)) <= n) k++;
    return k;
}

static inline void init_l1sp_data_regions() {
    for (int c = 0; c < g_total_cores; c++) {
        uintptr_t addr = 0;
        addr = ph_address_set_absolute(addr, 1);
        addr = ph_address_absolute_set_core(addr, (uintptr_t)c);
        addr = ph_address_absolute_set_l1sp_offset(addr, 0);
        g_l1sp_abs_base[c] = addr;
    }
    const uint64_t hart_cap = g_core_l1sp_bytes / (uint64_t)g_harts_per_core;
    if (hart_cap > L1SP_DATA_START + L1SP_STACK_GUARD) {
        g_l1sp_data_bytes_per_core = (int32_t)(hart_cap - L1SP_STACK_GUARD - L1SP_DATA_START);
    } else {
        g_l1sp_data_bytes_per_core = 0;
    }
}

// =====================================================================
// Utilities
// =====================================================================
static inline int get_thread_id() {
    return myCoreId() * myCoreThreads() + myThreadId();
}

static inline void spin_pause(int64_t iters) {
    for (int64_t i = 0; i < iters; i++) {
        asm volatile("" ::: "memory");
    }
}

static inline void barrier() {
    int tid = get_thread_id();
    int total = g_total_harts;

    int64_t local = g_local_sense[tid];
    local ^= 1;
    g_local_sense[tid] = local;

    int64_t old = g_count.fetch_add(1, std::memory_order_acq_rel);
    if (old == total - 1) {
        g_count.store(0, std::memory_order_relaxed);
        g_sense.store(local, std::memory_order_release);
    } else {
        long w = 1;
        long wmax = 64 * total;
        while (g_sense.load(std::memory_order_acquire) != local) {
            if (w < wmax) w <<= 1;
            hartsleep(w);
        }
    }
}

static inline void queue_init(WorkQueue* q) {
    q->head = 0;
    q->tail = 0;
    q->start_idx = 0;
}

static inline int64_t queue_depth(WorkQueue* q) {
    int64_t depth = atomic_load_i64(&q->tail) - atomic_load_i64(&q->head);
    return (depth > 0) ? depth : 0;
}

static inline void queue_assign_slice(WorkQueue* q, int64_t start_idx, int64_t count) {
    q->start_idx = start_idx;
    q->head = 0;
    q->tail = count;
}

extern "C" char l2sp_end[];

static inline uintptr_t align_up_uintptr(uintptr_t value, uintptr_t align) {
    return (value + align - 1) & ~(align - 1);
}

static void* try_alloc_l2sp(uintptr_t* heap, size_t bytes, size_t align, uintptr_t l2sp_limit) {
    const uintptr_t start = align_up_uintptr(*heap, (uintptr_t)align);
    const uintptr_t end = start + (uintptr_t)bytes;
    if (end > l2sp_limit) {
        return nullptr;
    }
    *heap = end;
    return (void*)start;
}

// =====================================================================
// Frontier accessors (L2SP → L1SP → DRAM)
// =====================================================================
static inline int64_t* frontier_current_ptr(int64_t idx) {
    if (idx < g_next_frontier.l2sp_capacity)
        return g_current_frontier_storage + idx;
    int64_t r = idx - g_next_frontier.l2sp_capacity;
    if (r < g_frontier_l1sp_capacity) {
        int core = (int)(r >> g_frontier_l1sp_shift);
        int local = (int)(r & ((1 << g_frontier_l1sp_shift) - 1));
        return (int64_t*)(g_l1sp_abs_base[core] + g_current_frontier_l1sp_offset) + local;
    }
    return g_current_frontier_dram_storage + (r - g_frontier_l1sp_capacity);
}

static inline int64_t frontier_current_get(int64_t idx) {
    return *frontier_current_ptr(idx);
}

static inline void frontier_current_set(int64_t idx, int64_t value) {
    *frontier_current_ptr(idx) = value;
}

static inline int64_t* frontier_next_item_ptr(int64_t idx) {
    if (idx < g_next_frontier.l2sp_capacity)
        return g_next_frontier.l2sp_items + idx;
    int64_t r = idx - g_next_frontier.l2sp_capacity;
    if (r < g_frontier_l1sp_capacity) {
        int core = (int)(r >> g_frontier_l1sp_shift);
        int local = (int)(r & ((1 << g_frontier_l1sp_shift) - 1));
        return (int64_t*)(g_l1sp_abs_base[core] + g_next_frontier_l1sp_offset) + local;
    }
    return g_next_frontier.dram_items + (r - g_frontier_l1sp_capacity);
}

static inline int64_t frontier_next_item_get(int64_t idx) {
    return *frontier_next_item_ptr(idx);
}

static inline void frontier_next_item_set(int64_t idx, int64_t value) {
    *frontier_next_item_ptr(idx) = value;
}

// =====================================================================
// Visited / dist accessors (L2SP → L1SP → DRAM)
// =====================================================================
static inline volatile int64_t* visited_ptr(int64_t idx) {
    if (idx < g_visited_l2sp_count)
        return visited + idx;
    int64_t r = idx - g_visited_l2sp_count;
    if (r < g_visited_l1sp_count) {
        int core = (int)(r >> g_visited_l1sp_shift);
        int local = (int)(r & ((1 << g_visited_l1sp_shift) - 1));
        return (volatile int64_t*)(g_l1sp_abs_base[core] + g_visited_l1sp_offset) + local;
    }
    return visited_dram + (r - g_visited_l1sp_count);
}

static inline int64_t visited_get(int64_t idx) {
    return *visited_ptr(idx);
}

static inline void visited_set(int64_t idx, int64_t value) {
    *visited_ptr(idx) = value;
}

static inline int32_t* dist_ptr(int64_t idx) {
    if (idx < g_dist_l2sp_count)
        return dist_arr + idx;
    int64_t r = idx - g_dist_l2sp_count;
    if (r < g_dist_l1sp_count) {
        int core = (int)(r >> g_dist_l1sp_shift);
        int local = (int)(r & ((1 << g_dist_l1sp_shift) - 1));
        return (int32_t*)(g_l1sp_abs_base[core] + g_dist_l1sp_offset) + local;
    }
    return dist_arr_dram + (r - g_dist_l1sp_count);
}

static inline int32_t dist_get(int64_t idx) {
    return *dist_ptr(idx);
}

static inline void dist_set(int64_t idx, int32_t value) {
    *dist_ptr(idx) = value;
}

static inline bool claim_node(int64_t v) {
    const int64_t old = atomic_swap_i64(visited_ptr(v), 1);
    return old == 0;
}

// =====================================================================
// Next frontier push (atomic)
// =====================================================================
static inline bool next_frontier_push_atomic(int64_t work) {
    int64_t idx = atomic_fetch_add_i64(&g_next_frontier.tail, 1);
    if (idx >= g_next_frontier.capacity) {
        return false;
    }
    frontier_next_item_set(idx, work);
    return true;
}

// =====================================================================
// Queue operations
// =====================================================================
// Batch pop: reserve up to max_chunk items from head via CAS.
static inline int64_t queue_pop_chunk(WorkQueue* q, int core_id, int64_t* out_begin, int64_t max_chunk) {
    int64_t h = atomic_load_i64(&q->head);
    int64_t t = atomic_load_i64(&q->tail);
    if (h >= t) {
        core_has_work[core_id] = 0;
        return 0;
    }
    int64_t avail = t - h;
    int64_t chunk = (avail < max_chunk) ? avail : max_chunk;
    int64_t old_h = atomic_compare_and_swap_i64(&q->head, h, h + chunk);
    if (old_h == h) {
        *out_begin = h;
        return chunk;
    }
    return 0;
}

// Steal half: try to take half of the victim's remaining queue
static inline int64_t queue_steal_half(WorkQueue* q, int core_id, int64_t* out_begin) {
    int64_t h = atomic_load_i64(&q->head);
    int64_t t = atomic_load_i64(&q->tail);
    if (h >= t) {
        core_has_work[core_id] = 0;
        return 0;
    }
    int64_t avail = t - h;
    int64_t steal_count = avail / 2;
    if (steal_count < 1) steal_count = 1;
    if (steal_count > STEAL_BATCH) steal_count = STEAL_BATCH;
    int64_t old_h = atomic_compare_and_swap_i64(&q->head, h, h + steal_count);
    if (old_h == h) {
        *out_begin = h;
        return steal_count;
    }
    return 0;
}

// =====================================================================
// L1SP stack usage tracking
// =====================================================================
static inline uint64_t current_stack_usage_bytes() {
    uintptr_t sp = 0;
    asm volatile("mv %0, sp" : "=r"(sp));
    const uint64_t hart_capacity = g_hart_stack_capacity_bytes;
    uint64_t l1sp_base = 0;
    asm volatile("csrr %0, " __stringify(MCSR_L1SPBASE) : "=r"(l1sp_base));
    const uint64_t stack_top =
        l1sp_base + (uint64_t)g_core_l1sp_bytes - ((uint64_t)myThreadId() * hart_capacity);
    if ((uint64_t)sp >= stack_top || hart_capacity == 0) return 0;
    uint64_t used = stack_top - (uint64_t)sp;
    if (used > hart_capacity) used = hart_capacity;
    return used;
}

static inline void track_stack_peak(int tid) {
    const uint64_t used = current_stack_usage_bytes();
    if (used > g_hart_stack_peak_bytes[tid]) {
        g_hart_stack_peak_bytes[tid] = used;
    }
}

// =====================================================================
// Victim selection PRNG
// =====================================================================
static inline uint32_t xorshift_victim(uint32_t seed) {
    seed ^= seed << 13;
    seed ^= seed >> 17;
    seed ^= seed << 5;
    return seed;
}

// =====================================================================
// Process a single BFS node
// =====================================================================
static inline int64_t process_single_node(int64_t u, int32_t level) {
    const int32_t row_start = g_row_ptr[u];
    const int32_t row_end = g_row_ptr[u + 1];
    int64_t edges_done = 0;
    for (int32_t ei = row_start; ei < row_end; ei++) {
        const int64_t v = g_col_idx[ei];
        edges_done++;
        if (claim_node(v)) {
            dist_set(v, level + 1);
            if (!next_frontier_push_atomic(v)) {
                std::printf("ERROR: next frontier overflow at level %d\n", level);
                std::abort();
            }
            atomic_fetch_add_i64(&discovered, 1);
        }
    }
    return edges_done;
}

// =====================================================================
// BFS Level Processing with SHARED QUEUE Work Stealing
//
// Strategy for PERFECT balance:
// - ALL frontier is placed in a single shared queue (same all-to-core-0 start)
// - ALL harts across ALL cores pop from the shared queue via CAS
// - This achieves perfect load distribution: whoever finishes first grabs more work
// - CAS batch pops (BFS_CHUNK_SIZE nodes per CAS) amortize contention
// =====================================================================
static void process_bfs_level(int tid, int32_t level) {
    const int harts_per_core = g_harts_per_core;
    const int my_core = tid / harts_per_core;

    int64_t local_processed = 0;
    int64_t local_edges = 0;

    for (;;) {
        // Pop a batch from the shared queue
        int64_t h = atomic_load_i64(&shared_queue.head);
        int64_t t = atomic_load_i64(&shared_queue.tail);
        if (h >= t) break;

        int64_t avail = t - h;
        int64_t chunk = (avail < BFS_CHUNK_SIZE) ? avail : BFS_CHUNK_SIZE;
        int64_t old_h = atomic_compare_and_swap_i64(&shared_queue.head, h, h + chunk);
        if (old_h != h) continue;  // CAS failed, retry

        for (int64_t i = 0; i < chunk; i++) {
            int64_t u = frontier_current_get(shared_queue.start_idx + h + i);
            local_processed++;
            local_edges += process_single_node(u, level);
        }
    }

    // Accumulate per-core stats atomically
    atomic_fetch_add_i64(&stat_nodes_processed_per_core[my_core], local_processed);
    atomic_fetch_add_i64(&stat_edges_traversed_per_core[my_core], local_edges);
    stat_nodes_processed[tid] += local_processed;
}

// =====================================================================
// Level advance: ALL-TO-SHARED-QUEUE distribution
//
// ALL frontier vertices are placed in one shared queue.
// Work stealing in process_bfs_level dynamically rebalances this.
// =====================================================================
static void advance_to_next_level_skewed(int tid) {
    if (tid != 0) return;

    int total_cores = g_total_cores;
    int64_t total_nodes = g_next_frontier.tail;

    if (total_nodes == 0) {
        queue_init(&shared_queue);
        g_next_frontier.tail = 0;
        return;
    }

    // Copy ALL nodes into current frontier starting at offset 0
    for (int64_t i = 0; i < total_nodes; i++) {
        frontier_current_set(i, frontier_next_item_get(i));
    }

    // ALL work goes into the shared queue — all harts pop from it
    queue_assign_slice(&shared_queue, 0, total_nodes);

    g_next_frontier.tail = 0;
}

// =====================================================================
// Graph loading (from binary CSR file)
// =====================================================================
static bool load_graph_from_file() {
    char fname[32];
    const char *src = "rmat_r16.bin";
    int fi = 0;
    while (src[fi]) { fname[fi] = src[fi]; fi++; }
    fname[fi] = '\0';

    int32_t header[5];
    struct ph_bulk_load_desc header_desc;
    header_desc.filename_addr = (long)fname;
    header_desc.dest_addr     = (long)header;
    header_desc.size          = (long)sizeof(header);
    header_desc.result        = 0;
    ph_bulk_load_file(&header_desc);

    if (header_desc.result <= 0) {
        std::printf("ERROR: bulk load of %s header failed (result=%ld)\n",
                    src, header_desc.result);
        return false;
    }

    int hdr_N      = header[0];
    int hdr_E      = header[1];
    int hdr_D      = header[2];
    int hdr_source = header[4];

    if (hdr_N <= 0 || hdr_E < 0) {
        std::printf("ERROR: invalid CSR header: N=%d E=%d D=%d source=%d\n",
                    src, hdr_N, hdr_E, hdr_D, hdr_source);
        return false;
    }

    const size_t file_size = 20
        + (size_t)(hdr_N + 1) * sizeof(int32_t)
        + (size_t)hdr_E * sizeof(int32_t)
        + (size_t)hdr_N * sizeof(int32_t);

    char *buf = (char *)std::malloc(file_size);
    if (!buf) {
        std::printf("ERROR: malloc failed for file buffer (%lu bytes)\n",
                    (unsigned long)file_size);
        return false;
    }

    struct ph_bulk_load_desc desc;
    desc.filename_addr = (long)fname;
    desc.dest_addr     = (long)buf;
    desc.size          = (long)file_size;
    desc.result        = 0;
    ph_bulk_load_file(&desc);

    if (desc.result <= 0) {
        std::printf("ERROR: bulk load of %s failed (result=%ld)\n", src, desc.result);
        std::free(buf);
        return false;
    }

    g_file_buffer  = buf;
    g_num_vertices = hdr_N;
    g_num_edges    = hdr_E;
    g_bfs_source   = hdr_source;

    // CSR arrays point into loaded buffer (DRAM via malloc)
    g_row_ptr = (int32_t *)(buf + 20);
    g_col_idx = (int32_t *)(buf + 20 + (size_t)(hdr_N + 1) * sizeof(int32_t));

    // Use highest-degree vertex as BFS source — maximizes initial imbalance
    // on power-law RMAT graphs (hub vertex produces massive first frontier)
    int32_t max_deg = -1;
    int32_t max_deg_vertex = 0;
    for (int32_t v = 0; v < hdr_N; v++) {
        const int32_t deg = g_row_ptr[v + 1] - g_row_ptr[v];
        if (deg > max_deg) {
            max_deg = deg;
            max_deg_vertex = v;
        }
    }
    g_bfs_source = max_deg_vertex;

    // --- Allocate visited/dist/frontier: L2SP → L1SP → DRAM ---
    uintptr_t l2sp_heap = align_up_uintptr((uintptr_t)l2sp_end, 8);
    const uintptr_t l2sp_base = 0x20000000;
    const uintptr_t l2sp_limit = l2sp_base + podL2SPSize();

    // L1SP data region heap (offset within each core's L1SP)
    uintptr_t l1sp_heap_off = L1SP_DATA_START;
    const uintptr_t l1sp_data_end = L1SP_DATA_START + (uintptr_t)g_l1sp_data_bytes_per_core;

    // Visited array
    g_visited_l2sp_count = 0;
    g_visited_l1sp_count = 0;
    visited = nullptr;
    visited_dram = nullptr;
    {
        const uintptr_t avail = (l2sp_heap < l2sp_limit) ? (l2sp_limit - l2sp_heap) : 0;
        int32_t l2sp_verts = (int32_t)((avail / sizeof(int64_t)) > (uintptr_t)hdr_N
            ? hdr_N : (avail / sizeof(int64_t)));
        if (l2sp_verts > 0) {
            visited = (volatile int64_t *)try_alloc_l2sp(
                &l2sp_heap, (size_t)l2sp_verts * sizeof(int64_t), alignof(int64_t), l2sp_limit);
        }
        g_visited_l2sp_count = (visited != nullptr) ? l2sp_verts : 0;
        int32_t remaining = hdr_N - g_visited_l2sp_count;

        // L1SP tier for remaining visited entries
        if (remaining > 0 && l1sp_heap_off < l1sp_data_end) {
            int32_t avail_bytes = (int32_t)(l1sp_data_end - l1sp_heap_off);
            int32_t entries_raw = avail_bytes / (int32_t)sizeof(int64_t);
            int32_t epc = floor_pow2(entries_raw);  // entries per core
            if (epc > 0) {
                int32_t total = epc * g_total_cores;
                if (total > remaining) {
                    epc = floor_pow2(remaining / g_total_cores);
                    total = epc * g_total_cores;
                }
                if (epc > 0) {
                    g_visited_l1sp_count = total;
                    g_visited_l1sp_per_core = epc;
                    g_visited_l1sp_shift = ilog2_pow2(epc);
                    g_visited_l1sp_offset = l1sp_heap_off;
                    l1sp_heap_off += (uintptr_t)epc * sizeof(int64_t);
                }
            }
            remaining = hdr_N - g_visited_l2sp_count - g_visited_l1sp_count;
        }

        if (remaining > 0) {
            visited_dram = (volatile int64_t *)std::malloc(
                (size_t)remaining * sizeof(int64_t));
        }
    }

    // Dist array
    g_dist_l2sp_count = 0;
    g_dist_l1sp_count = 0;
    dist_arr = nullptr;
    dist_arr_dram = nullptr;
    {
        const uintptr_t avail = (l2sp_heap < l2sp_limit) ? (l2sp_limit - l2sp_heap) : 0;
        int32_t l2sp_verts = (int32_t)((avail / sizeof(int32_t)) > (uintptr_t)hdr_N
            ? hdr_N : (avail / sizeof(int32_t)));
        if (l2sp_verts > 0) {
            dist_arr = (int32_t *)try_alloc_l2sp(
                &l2sp_heap, (size_t)l2sp_verts * sizeof(int32_t), alignof(int32_t), l2sp_limit);
        }
        g_dist_l2sp_count = (dist_arr != nullptr) ? l2sp_verts : 0;
        int32_t remaining = hdr_N - g_dist_l2sp_count;

        // L1SP tier for remaining dist entries
        if (remaining > 0 && l1sp_heap_off < l1sp_data_end) {
            int32_t avail_bytes = (int32_t)(l1sp_data_end - l1sp_heap_off);
            int32_t entries_raw = avail_bytes / (int32_t)sizeof(int32_t);
            int32_t epc = floor_pow2(entries_raw);
            if (epc > 0) {
                int32_t total = epc * g_total_cores;
                if (total > remaining) {
                    epc = floor_pow2(remaining / g_total_cores);
                    total = epc * g_total_cores;
                }
                if (epc > 0) {
                    g_dist_l1sp_count = total;
                    g_dist_l1sp_per_core = epc;
                    g_dist_l1sp_shift = ilog2_pow2(epc);
                    g_dist_l1sp_offset = l1sp_heap_off;
                    l1sp_heap_off += (uintptr_t)epc * sizeof(int32_t);
                }
            }
            remaining = hdr_N - g_dist_l2sp_count - g_dist_l1sp_count;
        }

        if (remaining > 0) {
            dist_arr_dram = (int32_t *)std::malloc(
                (size_t)remaining * sizeof(int32_t));
        }
    }

    {
        const int32_t vis_dram_count = hdr_N - g_visited_l2sp_count - g_visited_l1sp_count;
        const int32_t dist_dram_count = hdr_N - g_dist_l2sp_count - g_dist_l1sp_count;
        if ((g_visited_l2sp_count > 0 && !visited) ||
            (vis_dram_count > 0 && !visited_dram) ||
            (g_dist_l2sp_count > 0 && !dist_arr) ||
            (dist_dram_count > 0 && !dist_arr_dram)) {
            std::printf("ERROR: allocation failed for visited/dist\n");
            std::free(buf);
            std::free((void *)visited_dram);
            std::free(dist_arr_dram);
            return false;
        }
    }

    // Frontier buffers (L2SP → L1SP → DRAM)
    g_frontier_l1sp_capacity = 0;
    {
        const uintptr_t frontier_heap = align_up_uintptr(l2sp_heap, alignof(int64_t));
        const uintptr_t frontier_avail =
            (frontier_heap < l2sp_limit) ? (l2sp_limit - frontier_heap) : 0;
        // Each frontier vertex needs 2 * sizeof(int64_t) (current + next)
        const int64_t l2sp_verts =
            (int64_t)((frontier_avail / (2 * sizeof(int64_t))) > (uintptr_t)hdr_N
                ? hdr_N : (frontier_avail / (2 * sizeof(int64_t))));

        g_next_frontier.l2sp_capacity = l2sp_verts;
        g_next_frontier.l1sp_capacity = 0;
        g_current_frontier_storage = nullptr;
        g_current_frontier_dram_storage = nullptr;
        g_next_frontier.l2sp_items = nullptr;
        g_next_frontier.dram_items = nullptr;

        if (l2sp_verts > 0) {
            const size_t bytes = (size_t)l2sp_verts * sizeof(int64_t);
            g_current_frontier_storage =
                (int64_t *)try_alloc_l2sp(&l2sp_heap, bytes, alignof(int64_t), l2sp_limit);
            g_next_frontier.l2sp_items =
                (int64_t *)try_alloc_l2sp(&l2sp_heap, bytes, alignof(int64_t), l2sp_limit);
        }

        int64_t remaining = hdr_N - l2sp_verts;

        // L1SP tier for frontier buffers (current + next each need their own region)
        if (remaining > 0 && l1sp_heap_off < l1sp_data_end) {
            int32_t avail_bytes = (int32_t)(l1sp_data_end - l1sp_heap_off);
            // Need space for BOTH current and next frontier
            int32_t entries_raw = avail_bytes / (int32_t)(2 * sizeof(int64_t));
            int32_t epc = floor_pow2(entries_raw);
            if (epc > 0) {
                int64_t total = (int64_t)epc * g_total_cores;
                if (total > remaining) {
                    epc = floor_pow2((int32_t)(remaining / g_total_cores));
                    total = (int64_t)epc * g_total_cores;
                }
                if (epc > 0) {
                    g_frontier_l1sp_capacity = total;
                    g_frontier_l1sp_per_core = epc;
                    g_frontier_l1sp_shift = ilog2_pow2(epc);
                    g_current_frontier_l1sp_offset = l1sp_heap_off;
                    g_next_frontier_l1sp_offset = l1sp_heap_off + (uintptr_t)epc * sizeof(int64_t);
                    g_next_frontier.l1sp_capacity = total;
                    l1sp_heap_off += (uintptr_t)epc * 2 * sizeof(int64_t);
                }
            }
            remaining = hdr_N - l2sp_verts - g_frontier_l1sp_capacity;
        }

        if (remaining > 0) {
            const size_t bytes = (size_t)remaining * sizeof(int64_t);
            g_current_frontier_dram_storage = (int64_t *)std::malloc(bytes);
            g_next_frontier.dram_items = (int64_t *)std::malloc(bytes);
        }
        g_next_frontier.tail = 0;
        g_next_frontier.capacity = hdr_N;

        const bool missing_l2sp =
            l2sp_verts > 0 && (!g_current_frontier_storage || !g_next_frontier.l2sp_items);
        const int64_t dram_verts = hdr_N - l2sp_verts - g_frontier_l1sp_capacity;
        const bool missing_dram =
            dram_verts > 0 && (!g_current_frontier_dram_storage || !g_next_frontier.dram_items);
        if (missing_l2sp || missing_dram) {
            std::printf("ERROR: allocation failed for frontier buffers\n");
            std::free(buf);
            std::free((void *)visited_dram);
            std::free(dist_arr_dram);
            std::free(g_current_frontier_dram_storage);
            std::free(g_next_frontier.dram_items);
            return false;
        }
    }

    std::printf("Graph loaded: N=%d E=%d source=%d (max_deg=%d)\n",
                hdr_N, hdr_E, g_bfs_source, max_deg);
    return true;
}

// =====================================================================
// L2SP Utilization Report
// =====================================================================
static void report_l2sp_utilization() {
    const uintptr_t l2sp_base = 0x20000000;
    const uint64_t l2sp_total = podL2SPSize();
    const uintptr_t l2sp_limit = l2sp_base + l2sp_total;
    uintptr_t l2sp_heap = align_up_uintptr((uintptr_t)l2sp_end, 8);

    // Static L2SP usage (globals with __l2sp__)
    const uint64_t static_bytes = (uintptr_t)l2sp_end - l2sp_base;

    // Dynamic L2SP usage
    const uint64_t visited_l2sp_bytes = (uint64_t)g_visited_l2sp_count * sizeof(int64_t);
    const uint64_t dist_l2sp_bytes = (uint64_t)g_dist_l2sp_count * sizeof(int32_t);
    const uint64_t frontier_l2sp_bytes = (uint64_t)g_next_frontier.l2sp_capacity * 2 * sizeof(int64_t);
    const uint64_t dynamic_bytes = visited_l2sp_bytes + dist_l2sp_bytes + frontier_l2sp_bytes;
    const uint64_t total_used = static_bytes + dynamic_bytes;

    const uint64_t pct_used = (l2sp_total > 0) ? (total_used * 100 / l2sp_total) : 0;
    const uint64_t pct_frac  = (l2sp_total > 0) ? ((total_used * 1000 / l2sp_total) % 10) : 0;

    std::printf("\n========== L2SP UTILIZATION ==========\n");
    std::printf("L2SP total:           %lu bytes\n", (unsigned long)l2sp_total);
    std::printf("L2SP used (total):    %lu bytes (%lu.%lu%%)\n",
                (unsigned long)total_used,
                (unsigned long)pct_used, (unsigned long)pct_frac);
    std::printf("  Static globals:     %lu bytes\n", (unsigned long)static_bytes);
    std::printf("    - WorkQueues:     %lu bytes (%d cores)\n",
                (unsigned long)(sizeof(WorkQueue) * g_total_cores), g_total_cores);
    std::printf("    - Barrier state:  %lu bytes\n",
                (unsigned long)(sizeof(int64_t) * g_total_harts + 2 * sizeof(std::atomic<int64_t>)));
    std::printf("    - core_has_work:  %lu bytes\n",
                (unsigned long)(sizeof(int32_t) * g_total_cores));
    std::printf("    - Per-core stats: %lu bytes\n",
                (unsigned long)(5 * sizeof(int64_t) * g_total_cores));
    std::printf("  Dynamic allocs:\n");
    std::printf("    - visited[]:      %lu bytes (%d/%d vertices in L2SP)\n",
                (unsigned long)visited_l2sp_bytes, g_visited_l2sp_count, g_num_vertices);
    std::printf("    - dist_arr[]:     %lu bytes (%d/%d vertices in L2SP)\n",
                (unsigned long)dist_l2sp_bytes, g_dist_l2sp_count, g_num_vertices);
    std::printf("    - Frontier bufs:  %lu bytes (%ld/%d vertices in L2SP)\n",
                (unsigned long)frontier_l2sp_bytes,
                (long)g_next_frontier.l2sp_capacity, g_num_vertices);
    std::printf("L2SP free:            %lu bytes\n",
                (unsigned long)(l2sp_total - total_used));

    // L1SP data tier summary
    const uint64_t vis_l1sp_bytes = (uint64_t)g_visited_l1sp_count * sizeof(int64_t);
    const uint64_t dist_l1sp_bytes = (uint64_t)g_dist_l1sp_count * sizeof(int32_t);
    const uint64_t frontier_l1sp_bytes = (uint64_t)g_frontier_l1sp_capacity * 2 * sizeof(int64_t);
    const uint64_t l1sp_data_total = vis_l1sp_bytes + dist_l1sp_bytes + frontier_l1sp_bytes;
    std::printf("\nL1SP data tier:       %lu bytes across %d cores (%d bytes/core usable)\n",
                (unsigned long)l1sp_data_total, g_total_cores, g_l1sp_data_bytes_per_core);
    if (g_visited_l1sp_count > 0)
        std::printf("    - visited[]:      %lu bytes (%d vertices, %d/core)\n",
                    (unsigned long)vis_l1sp_bytes, g_visited_l1sp_count, g_visited_l1sp_per_core);
    if (g_dist_l1sp_count > 0)
        std::printf("    - dist_arr[]:     %lu bytes (%d vertices, %d/core)\n",
                    (unsigned long)dist_l1sp_bytes, g_dist_l1sp_count, g_dist_l1sp_per_core);
    if (g_frontier_l1sp_capacity > 0)
        std::printf("    - Frontier bufs:  %lu bytes (%ld vertices, %d/core)\n",
                    (unsigned long)frontier_l1sp_bytes,
                    (long)g_frontier_l1sp_capacity, g_frontier_l1sp_per_core);
    if (l1sp_data_total == 0)
        std::printf("    (no L1SP overflow needed — all data fits in L2SP)\n");

    // DRAM overflow summary
    const int32_t vis_dram = g_num_vertices - g_visited_l2sp_count - g_visited_l1sp_count;
    const int32_t dist_dram = g_num_vertices - g_dist_l2sp_count - g_dist_l1sp_count;
    const int64_t frontier_dram = g_num_vertices - g_next_frontier.l2sp_capacity - g_frontier_l1sp_capacity;
    if (vis_dram > 0 || dist_dram > 0 || frontier_dram > 0) {
        std::printf("\nDRAM overflow:\n");
        if (vis_dram > 0)
            std::printf("    - visited[]:      %lu bytes (%d vertices)\n",
                        (unsigned long)((uint64_t)vis_dram * sizeof(int64_t)), vis_dram);
        if (dist_dram > 0)
            std::printf("    - dist_arr[]:     %lu bytes (%d vertices)\n",
                        (unsigned long)((uint64_t)dist_dram * sizeof(int32_t)), dist_dram);
        if (frontier_dram > 0)
            std::printf("    - Frontier bufs:  %lu bytes (%ld vertices)\n",
                        (unsigned long)((uint64_t)frontier_dram * 2 * sizeof(int64_t)),
                        (long)frontier_dram);
    }
    std::printf("======================================\n");
}

// =====================================================================
// L1SP Utilization Report
// =====================================================================
static void report_l1sp_utilization() {
    const uint64_t core_l1sp = g_core_l1sp_bytes;
    const uint64_t global_l1sp = core_l1sp * (uint64_t)g_total_cores;
    const uint64_t thief_token_bytes = 8;  // one int64_t at L1SP base
    const uint64_t hart_cap = g_hart_stack_capacity_bytes;

    std::printf("\n========== L1SP UTILIZATION ==========\n");
    std::printf("L1SP per-core:        %lu bytes\n", (unsigned long)core_l1sp);
    std::printf("L1SP global:          %lu bytes (%d cores)\n",
                (unsigned long)global_l1sp, g_total_cores);
    std::printf("L1SP contents per core:\n");
    std::printf("  [0x000] Thief token: %lu bytes (work-stealing coordination)\n",
                (unsigned long)thief_token_bytes);
    if (g_l1sp_data_bytes_per_core > 0) {
        const uint64_t data_used_per_core =
            (uint64_t)g_visited_l1sp_per_core * sizeof(int64_t) +
            (uint64_t)g_dist_l1sp_per_core * sizeof(int32_t) +
            (uint64_t)g_frontier_l1sp_per_core * 2 * sizeof(int64_t);
        std::printf("  [0x%03lx-0x%03lx] Data region: %d bytes usable, %lu used\n",
                    (unsigned long)L1SP_DATA_START,
                    (unsigned long)(L1SP_DATA_START + g_l1sp_data_bytes_per_core),
                    g_l1sp_data_bytes_per_core,
                    (unsigned long)data_used_per_core);
    }
    std::printf("  [stack] Per-hart stacks: %d harts x %lu bytes = %lu bytes\n",
                g_harts_per_core, (unsigned long)hart_cap,
                (unsigned long)(hart_cap * (uint64_t)g_harts_per_core));
    std::printf("  Stack guard: %lu bytes (protects data from stack growth)\n",
                (unsigned long)L1SP_STACK_GUARD);

    std::printf("\nPer-hart peak stack usage:\n");
    for (int c = 0; c < g_total_cores; c++) {
        std::printf("  Core %d:", c);
        uint64_t core_peak_total = 0;
        for (int t = 0; t < g_harts_per_core; t++) {
            int h = c * g_harts_per_core + t;
            uint64_t peak = g_hart_stack_peak_bytes[h];
            core_peak_total += peak;
            if (t < 4 || peak > 0) {
                std::printf(" h%d=%lu", t, (unsigned long)peak);
            }
        }
        uint64_t core_pct = (core_l1sp > 0) ? (core_peak_total * 100 / core_l1sp) : 0;
        std::printf("  (core total peak: %lu / %lu bytes, %lu%%)\n",
                    (unsigned long)core_peak_total,
                    (unsigned long)core_l1sp,
                    (unsigned long)core_pct);
    }
    std::printf("======================================\n");
}

// =====================================================================
// Per-core work balance report
// =====================================================================
static void report_work_balance() {
    std::printf("\n========== WORK BALANCE (per-core) ==========\n");
    std::printf("Core | Nodes Processed | Edges Traversed | Stolen Nodes | Steal OK/Attempts\n");
    std::printf("-----|-----------------|-----------------|--------------|------------------\n");

    int64_t total_nodes = 0;
    int64_t total_edges = 0;
    int64_t total_stolen = 0;
    int64_t min_nodes = INT64_MAX;
    int64_t max_nodes = 0;

    for (int c = 0; c < g_total_cores; c++) {
        int64_t nodes = stat_nodes_processed_per_core[c];
        int64_t edges = stat_edges_traversed_per_core[c];
        int64_t stolen = stat_stolen_nodes_per_core[c];
        int64_t attempts = stat_steal_attempts_per_core[c];
        int64_t success = stat_steal_success_per_core[c];

        std::printf("  %2d | %15ld | %15ld | %12ld | %ld/%ld\n",
                    c, (long)nodes, (long)edges, (long)stolen,
                    (long)success, (long)attempts);

        total_nodes += nodes;
        total_edges += edges;
        total_stolen += stolen;
        if (nodes < min_nodes) min_nodes = nodes;
        if (nodes > max_nodes) max_nodes = nodes;
    }

    int64_t avg = (g_total_cores > 0) ? (total_nodes / g_total_cores) : 0;
    int64_t imbalance_pct = (max_nodes > 0) ? ((max_nodes - min_nodes) * 100 / max_nodes) : 0;

    std::printf("\nSummary:\n");
    std::printf("  Total nodes processed: %ld\n", (long)total_nodes);
    std::printf("  Total edges traversed: %ld\n", (long)total_edges);
    std::printf("  Total stolen nodes:    %ld\n", (long)total_stolen);
    std::printf("  Average per core:      %ld nodes\n", (long)avg);
    std::printf("  Min/Max per core:      %ld / %ld\n", (long)min_nodes, (long)max_nodes);
    std::printf("  Imbalance (max-min)/max: %ld%%\n", (long)imbalance_pct);
    if (imbalance_pct < 5) {
        std::printf("  >>> PERFECT BALANCE ACHIEVED <<<\n");
    }
    std::printf("=============================================\n");
}

// =====================================================================
// BFS Driver
// =====================================================================
static void bfs() {
    const int tid = get_thread_id();

    if (tid == 0) {
        // Set up L1SP sizing BEFORE graph loading (allocator needs it)
        g_core_l1sp_bytes = coreL1SPSize();
        g_hart_stack_capacity_bytes = g_core_l1sp_bytes / (uint64_t)g_harts_per_core;
        init_l1sp_data_regions();

        // Load graph
        if (!load_graph_from_file()) {
            std::abort();
        }

        const int32_t num_verts = g_num_vertices;
        const int64_t source_id = g_bfs_source;

        // Initialize per-hart stats
        for (int i = 0; i < g_total_harts; i++) {
            g_local_sense[i] = 0;
            stat_nodes_processed[i] = 0;
            g_hart_stack_peak_bytes[i] = 0;
        }

        // Initialize per-core stats and queues
        for (int c = 0; c < g_total_cores; c++) {
            queue_init(&core_queues[c]);
            core_has_work[c] = 0;
            stat_nodes_processed_per_core[c] = 0;
            stat_edges_traversed_per_core[c] = 0;
            stat_steal_attempts_per_core[c] = 0;
            stat_steal_success_per_core[c] = 0;
            stat_stolen_nodes_per_core[c] = 0;
        }
        g_next_frontier.tail = 0;
        discovered = 1;

        std::printf("\n");
        std::printf("=========================================================\n");
        std::printf("  BFS with Perfect Work Stealing — L1SP/L2SP Utilization\n");
        std::printf("=========================================================\n");
        std::printf("Graph: N=%d E=%d (RMAT power-law, highest imbalance)\n",
                    g_num_vertices, g_num_edges);
        std::printf("Source: vertex %ld (highest-degree hub)\n", (long)source_id);
        std::printf("Hardware: %d cores x %d harts = %d total harts\n",
                    g_total_cores, g_harts_per_core, g_total_harts);
        std::printf("\nMemory Layout:\n");
        std::printf("  L1SP: per-hart stack (%lu B each) + data overflow (%d B/core, %d cores)\n",
                    (unsigned long)g_hart_stack_capacity_bytes,
                    g_l1sp_data_bytes_per_core, g_total_cores);
        std::printf("  L2SP: shared work queue, frontier buffers, visited[], barriers\n");
        std::printf("  DRAM: CSR graph (row_ptr, col_idx), overflow arrays\n");
        std::printf("  Allocation: L2SP → L1SP (distributed) → DRAM\n");
        std::printf("=========================================================\n\n");

        g_initialized.store(1, std::memory_order_release);
    } else {
        while (g_initialized.load(std::memory_order_acquire) == 0) {
            hartsleep(10);
        }
    }

    // Each core's first hart initializes its L1SP thief token
    if (myThreadId() == 0) {
        thief_token_init();
    }

    // Parallel initialization of visited[] and dist[] — all harts participate
    // This is critical for large graphs (100K+ vertices) where serial init is a bottleneck
    {
        const int32_t num_verts = g_num_vertices;
        const int total = g_total_harts;
        const int64_t chunk = (num_verts + total - 1) / total;
        const int64_t my_start = (int64_t)tid * chunk;
        const int64_t my_end = (my_start + chunk < num_verts) ? (my_start + chunk) : num_verts;
        for (int64_t i = my_start; i < my_end; i++) {
            visited_set(i, 0);
            dist_set(i, -1);
        }
    }

    barrier();

    // Hart 0 marks source and sets up initial frontier AFTER parallel init
    if (tid == 0) {
        const int64_t source_id = g_bfs_source;
        visited_set(source_id, 1);
        dist_set(source_id, 0);
        queue_assign_slice(&shared_queue, 0, 1);
        frontier_current_set(0, source_id);
    }

    barrier();

    uint64_t start_cycles = 0;
    if (tid == 0) {
        asm volatile("rdcycle %0" : "=r"(start_cycles));
    }

    int32_t level = 0;

    while (true) {
        // Check total work in the shared queue
        int64_t total_work = shared_queue.tail - shared_queue.head;
        if (total_work < 0) total_work = 0;

        barrier();

        if (total_work == 0) break;

        if (tid == 0) {
            std::printf("Level %d: frontier=%ld, discovered=%ld\n",
                        level, (long)total_work, (long)discovered);
        }

        barrier();
        track_stack_peak(tid);
        barrier();

        process_bfs_level(tid, level);

        barrier();

        advance_to_next_level_skewed(tid);

        barrier();
        level++;
    }

    uint64_t end_cycles = 0;
    if (tid == 0) {
        asm volatile("rdcycle %0" : "=r"(end_cycles));
    }

    barrier();
    track_stack_peak(tid);
    barrier();

    if (tid == 0) {
        uint64_t elapsed = end_cycles - start_cycles;

        std::printf("\n=== BFS Complete ===\n");
        std::printf("Levels traversed: %d\n", level);
        std::printf("Nodes discovered: %ld / %d\n", (long)discovered, g_num_vertices);
        std::printf("Cycles elapsed:   %lu\n", (unsigned long)elapsed);
        if (discovered > 0) {
            std::printf("Cycles per node:  %lu\n",
                        (unsigned long)(elapsed / (uint64_t)discovered));
        }

        // Utilization reports
        report_l2sp_utilization();
        report_l1sp_utilization();
        report_work_balance();

        // Cleanup
        std::free(g_file_buffer);
        std::free((void *)visited_dram);
        std::free(dist_arr_dram);
        std::free(g_current_frontier_dram_storage);
        std::free(g_next_frontier.dram_items);
        g_file_buffer = nullptr;
        g_row_ptr     = nullptr;
        g_col_idx     = nullptr;
    }
}

// =====================================================================
// Entry point
// =====================================================================
int main(int argc, char** argv) {
    const int tid = get_thread_id();

    if (tid == 0) {
        g_total_cores = numPodCores();
        g_harts_per_core = myCoreThreads();
        g_total_harts = g_total_cores * g_harts_per_core;
    }

    barrier();
    bfs();
    barrier();

    return 0;
}
