// bfs_csr_weak_multi_roi.cpp
// ROI-only multi-pod CSR graph BFS: skips Phase 1 dist[] init by bulk-loading
// pre-generated dist[] array. Frontier bitmap init is kept in code (L2SP, cheap).
// Only simulates Phase 2 (BFS traversal loop).
//
// Pre-initialized files (generated by gen_bfs_init_state.py):
//   bfs_dist_init.bin - dist[] array (N int32, all -1 except source=0)
//
// Memory layout:
//   DRAM  – CSR graph, dist[], remote frontier exchange buffers, inter-pod sync
//   L2SP  – frontier bitmaps (2x), barrier, control variables (per-pod)

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <algorithm>

#include <pandohammer/cpuinfo.h>
#include <pandohammer/atomic.h>
#include <pandohammer/hartsleep.h>
#include <pandohammer/mmio.h>
#include <pandohammer/staticdecl.h>

// =============================================================================
// PART 1 — CONFIGURATION DEFAULTS
// =============================================================================
// Compile-time knobs and limits:
//   * DEFAULT_VTX_PER_THREAD / DEFAULT_DEGREE — fallbacks for --V / --D args.
//   * DO_FULL_VERIFY — if 1, pod 0 runs a triangle-inequality check over every
//                      edge after the BFS completes (expensive but exhaustive).
//   * MAX_PODS      — sizes the per-pod phase array used by the inter-pod
//                      barrier.
// -----------------------------------------------------------------------------
// ---------- Configuration defaults ----------
#ifndef DEFAULT_VTX_PER_THREAD
#define DEFAULT_VTX_PER_THREAD 1024
#endif

#ifndef DEFAULT_DEGREE
#define DEFAULT_DEGREE 16
#endif

static const int DO_FULL_VERIFY = 0;
static const int MAX_PODS = 8;

// =============================================================================
// PART 2 — L2SP SECTION ATTRIBUTE
// =============================================================================
// Macro that places a global into the linker section ".l2sp", which the
// PANDOHammer ABI maps into each pod's L2 scratchpad. Variables tagged
// __l2sp__ are pod-local (one copy per pod, not shared between pods) and
// get fast access for all harts on that pod.
// -----------------------------------------------------------------------------
// ---------- Section attribute ----------
#define __l2sp__ __attribute__((section(".l2sp")))

// =============================================================================
// PART 3 — LOW-LEVEL HELPERS
// =============================================================================
// Small utilities used throughout:
//   * atomic_or_i32 — inline RISC-V amoor.w, the primitive used for both
//                     local bitmap updates (L2SP next_frontier) AND remote
//                     updates (DRAM exchange buffer). "Blocking" = returns
//                     the old value; the store is committed before return.
//   * parse_i       — argv integer with default fallback.
//   * wait          — tight nop-loop backoff (used inside the intra-pod
//                     barrier's spin).
//   * bulk_load     — host-file -> simulated DRAM via ph_bulk_load_file
//                     MMIO. Used to load uniform_graph.bin and the pre-
//                     computed bfs_dist_init.bin (that pre-init is what
//                     makes this the "ROI-only" variant — see file header).
// -----------------------------------------------------------------------------
// ---------- Blocking atomic OR (standard RISC-V amoor.w) ----------
static inline int32_t atomic_or_i32(volatile int32_t *ptr, int32_t val)
{
    int32_t ret;
    asm volatile("amoor.w %0, %2, 0(%1)"
                 : "=r"(ret) : "r"(ptr), "r"(val) : "memory");
    return ret;
}

// ---------- Helpers ----------
static int parse_i(const char *s, int d)
{
    if (!s) return d;
    char *e = nullptr;
    long v = strtol(s, &e, 10);
    return (e && *e == 0) ? (int)v : d;
}

static inline void wait(volatile int x)
{
    for (int i = 0; i < x; i++)
        asm volatile("nop");
}

// ---------- Bulk load helper ----------
static void bulk_load(const char *name, void *dest, size_t size)
{
    char fname_buf[64];
    int fi = 0;
    while (name[fi] && fi < 63) { fname_buf[fi] = name[fi]; fi++; }
    fname_buf[fi] = '\0';

    struct ph_bulk_load_desc desc;
    desc.filename_addr = (long)fname_buf;
    desc.dest_addr     = (long)dest;
    desc.size          = (long)size;
    desc.result        = 0;
    ph_bulk_load_file(&desc);

    if (desc.result <= 0) {
        std::printf("ERROR: bulk load '%s' failed (result=%ld)\n", name, desc.result);
    }
}

// =============================================================================
// PART 4 — INTRA-POD BARRIER (L2SP)
// =============================================================================
// Fast barrier for all threads within a single pod. State lives in L2SP so
// every hart on the pod has cheap access:
//   * barrier_data    — raw POD struct: count / signal / num_threads.
//   * g_barrier_data  — the single instance (one per pod, lives in L2SP).
//   * barrier_ref     — thin wrapper that exposes .sync(). The pattern is
//                        the classic "sense-reversing" barrier: each thread
//                        atomic-adds to count; the last arrival runs an
//                        optional callback `f()` and flips `signal`. Losers
//                        spin on the old signal value with exponential
//                        backoff (wait() nop-loop) up to backoff_limit=1000
//                        to reduce memory-system pressure while waiting.
// This barrier is used dozens of times per BFS level — it MUST be cheap,
// which is why it is entirely L2SP-resident. Cross-pod synchronization uses
// the separate DRAM inter_pod_barrier below.
// -----------------------------------------------------------------------------
// ---------- Intra-pod Barrier (L2SP) ----------
struct barrier_data {
    int count;
    int signal;
    int num_threads;
};

__l2sp__ barrier_data g_barrier_data = {0, 0, 0};

class barrier_ref {
public:
    barrier_ref(barrier_data *ptr) : ptr_(ptr) {}
    barrier_data *ptr_;

    int &count()       { return ptr_->count; }
    int &signal()      { return ptr_->signal; }
    int &num_threads() { return ptr_->num_threads; }

    void sync() { sync([](){}); }

    template <typename F>
    void sync(F f) {
        int signal_ = signal();
        int count_  = atomic_fetch_add_i32(&count(), 1);
        if (count_ == num_threads() - 1) {
            count() = 0;
            f();
            signal() = !signal_;
        } else {
            static constexpr int backoff_limit = 1000;
            int backoff_counter = 8;
            while (signal() == signal_) {
                wait(backoff_counter);
                backoff_counter = std::min(backoff_counter * 2, backoff_limit);
            }
        }
    }
};

// =============================================================================
// PART 5 — INTER-POD BARRIER (DRAM)
// =============================================================================
// Cross-pod synchronization primitive. State is in DRAM because L2SP is
// pod-local and invisible to other pods.
//   * g_inter_pod_count   — shared 64-bit counter of arrivals in current phase.
//   * g_inter_pod_phase   — shared 64-bit phase number (incremented per release).
//   * g_pod_local_phase[] — each pod's remembered "my phase" value. Used so a
//                            pod that hasn't arrived yet spins until the shared
//                            phase advances past its own remembered value.
// Protocol: atomic fetch-add on count; the last arrival (old == num_pods-1)
// subtracts num_pods and bumps phase. Others hartsleep with exponential
// backoff (64 -> 2048) polling the phase. Only ONE hart per pod calls this
// (typically tid 0); other harts wait on the intra-pod barrier.
//
// NOTE: this barrier runs many times per BFS level, and each call touches
// DRAM — it is a major contributor to multi-pod overhead at scale.
// -----------------------------------------------------------------------------
// ---------- Inter-pod Barrier (DRAM) ----------
static volatile int64_t g_inter_pod_count = 0;
static volatile int64_t g_inter_pod_phase = 0;
static int64_t g_pod_local_phase[MAX_PODS];

static inline void inter_pod_barrier(int pod_id, int num_pods)
{
    int64_t my_phase = g_pod_local_phase[pod_id];

    int64_t old = atomic_fetch_add_i64(&g_inter_pod_count, 1);
    if (old == num_pods - 1) {
        atomic_fetch_add_i64(&g_inter_pod_count, -num_pods);
        atomic_fetch_add_i64(&g_inter_pod_phase, 1);
    } else {
        long w = 64, wmax = 2048;
        while (atomic_load_i64(&g_inter_pod_phase) == my_phase) {
            hartsleep(w);
            if (w < wmax) w <<= 1;
        }
    }
    g_pod_local_phase[pod_id] = my_phase + 1;
}

// =============================================================================
// PART 6 — DRAM GLOBALS FOR MULTI-POD COORDINATION
// =============================================================================
// Variables backed by DRAM so ALL pods see the same physical memory. These
// break into three groups:
//
// 1) Handshake / termination flags written by pod 0 tid 0 (init leader)
//    and polled by every other hart:
//      g_pods_ready          — 0=not ready, 1=init complete, -1=init failed.
//      g_global_done         — set by pod 0 when BFS frontier is globally empty.
//      g_global_any_work     — OR-reduction target: did any pod produce work
//                              this level? Cleared each iteration.
//      g_global_bfs_iters    — current BFS level counter (authoritative copy).
//      g_global_sim_exit     — final kill switch; parks non-participating
//                              harts until pod 0 signals shutdown.
//
// 2) g_remote_frontier — DRAM array of shape [num_pods][bm_words_local].
//    This is the inter-pod frontier exchange buffer. When a local hart
//    discovers a neighbor that lives on a REMOTE pod, it atomic-ORs a bit
//    into the remote pod's slice. After the inter-pod barrier, each pod
//    drains its own slice into its local next_frontier.
//
// 3) DRAM pointer/parameter shadow — g_dram_file_buffer, g_dram_csr_offsets,
//    g_dram_csr_edges, g_dram_dist, g_dram_N, g_dram_N_local, g_dram_degree,
//    g_dram_source, g_dram_total_threads_per_pod, g_dram_bm_words_local,
//    g_dram_num_pods. Pod 0 tid 0 allocates the graph buffers and writes
//    these; every other pod's tid 0 reads them into its L2SP copies in
//    Phase 0b. This avoids each pod bulk-loading the same file.
// -----------------------------------------------------------------------------
// ---------- DRAM globals for multi-pod coordination ----------
static volatile int32_t g_pods_ready = 0;
static volatile int32_t g_global_done = 0;
static volatile int32_t g_global_any_work = 0;
static volatile int32_t g_global_bfs_iters = 0;
static volatile int32_t g_global_sim_exit = 0;

// DRAM pointers set by pod 0 tid 0, read by all pods
static volatile int32_t *g_remote_frontier = nullptr; // [num_pods * bm_words_local]
static char    *g_dram_file_buffer = nullptr;
static int32_t *g_dram_csr_offsets = nullptr;
static int32_t *g_dram_csr_edges = nullptr;
static int32_t *g_dram_dist = nullptr;
static int32_t  g_dram_N = 0;
static int32_t  g_dram_N_local = 0;
static int32_t  g_dram_degree = 0;
static int32_t  g_dram_source = 0;
static int32_t  g_dram_total_threads_per_pod = 0;
static int32_t  g_dram_bm_words_local = 0;
static int32_t  g_dram_num_pods = 0;

// =============================================================================
// PART 7 — L2SP GLOBALS (PER-POD)
// =============================================================================
// Per-pod shadow of DRAM parameters plus per-pod state. One copy per pod,
// living in the pod's L2 scratchpad for fast access by every hart on that
// pod. All are populated by tid 0 in Phase 0b from the DRAM copies.
//
//   Topology / sizing (read-only after Phase 0b):
//     g_N, g_N_local, g_vtx_offset, g_degree, g_total_threads,
//     g_bitmap_words, g_pod_id, g_num_pods
//
//   Per-iteration control flags (written by tid 0, read by peers):
//     g_bfs_done      — set when global BFS completes; signals loop exit.
//     g_sim_exit      — set at the very end; non-pod-0 wait on this.
//     g_any_work      — OR-reduced per-pod "did we push anything" flag.
//
//   Per-pod reduction accumulators (filled in Phase 3, drained to DRAM):
//     g_sum_dist, g_reached, g_max_dist
//
//   DRAM pointer cache (fast local read of pointers, deref still goes to DRAM):
//     g_csr_offsets, g_csr_edges, g_dist, g_source
//
//   Frontier bitmaps (L2SP, double-buffered):
//     g_frontier      — current level's bitmap.
//     g_next_frontier — build target for the next level; swap at end of level.
//
//   g_my_remote_frontier — pointer into g_remote_frontier at THIS pod's
//                           slice. During the "merge remote" step, each
//                           thread drains a word-range from this slice
//                           into g_next_frontier and posts a zero back.
//
//   l2sp_end — linker-provided symbol marking the end of static .l2sp data.
//              The frontier bitmaps are allocated dynamically starting here
//              (see Phase 0b), so their size scales with N_local.
// -----------------------------------------------------------------------------
// ---------- L2SP globals (per-pod) ----------
__l2sp__ int32_t g_N;                  // total vertices (global)
__l2sp__ int32_t g_N_local;            // vertices owned by this pod
__l2sp__ int32_t g_vtx_offset;         // first vertex owned by this pod
__l2sp__ int32_t g_degree;
__l2sp__ int32_t g_total_threads;      // threads per pod
__l2sp__ int32_t g_bitmap_words;       // ceil(N_local/32)
__l2sp__ int32_t g_pod_id;
__l2sp__ int32_t g_num_pods;

__l2sp__ volatile int g_bfs_done;
__l2sp__ volatile int g_sim_exit;
__l2sp__ volatile int32_t g_any_work;

// Reduction accumulators (per-pod, then combined in DRAM)
__l2sp__ volatile int64_t g_sum_dist;
__l2sp__ volatile int32_t g_reached;
__l2sp__ volatile int32_t g_max_dist;

// DRAM array pointers cached in L2SP
__l2sp__ int32_t *g_csr_offsets;
__l2sp__ int32_t *g_csr_edges;
__l2sp__ int32_t *g_dist;
__l2sp__ int32_t  g_source;

// L2SP bitmap pointers (dynamically allocated from L2SP heap)
__l2sp__ volatile int32_t *g_frontier;
__l2sp__ volatile int32_t *g_next_frontier;

// Pointer to this pod's remote frontier exchange buffer in DRAM
__l2sp__ volatile int32_t *g_my_remote_frontier;

// Linker symbol: first free byte in L2SP after static data
extern "C" char l2sp_end[];

// =============================================================================
// PART 8 — GLOBAL REDUCTION ACCUMULATORS IN DRAM
// =============================================================================
// Cross-pod final reduction targets. Each pod first reduces its own
// partition into its per-pod L2SP accumulators (g_sum_dist, g_reached,
// g_max_dist), then pod leaders (tid 0) fold those into these DRAM
// variables using atomic-add (for sum/count) and CAS-loop-max (for max).
// Pod 0 tid 0 reads and prints these in Phase 4.
// -----------------------------------------------------------------------------
// ---------- Global reduction accumulators in DRAM ----------
static volatile int64_t g_global_sum_dist = 0;
static volatile int32_t g_global_reached = 0;
static volatile int32_t g_global_max_dist = 0;

// =============================================================================
// PART 9 — MAIN (per-hart entry point + multi-pod BFS driver)
// =============================================================================
// Every hart on every pod enters main(). Flow:
//
//   Preamble
//     * Parse --V / --D / --T from argv.
//     * Read hardware topology (pxn/pod/core/hart ids, counts).
//     * Compute local tid within pod and clamp active thread count to
//       `threads_per_pod`.
//     * Park non-pxn-0 harts and harts whose tid >= total_threads. They
//       hartsleep until g_global_sim_exit is raised at the end.
//     * Derive per-pod N_local, total N, and bitmap word count.
//
//   Phase 0a — Pod 0, tid 0 only: DRAM bulk-load & global setup
//     * malloc() the graph file buffer and bulk_load("uniform_graph.bin").
//     * Parse the 20-byte header; sanity-check N and E against expected.
//     * malloc() dist[] and bulk_load("bfs_dist_init.bin") — pre-initialized
//       (all -1 with source=0). THIS IS WHAT MAKES THIS THE "ROI-ONLY"
//       VARIANT: dist[] init is NOT simulated, only the BFS loop is.
//     * malloc() and zero the per-pod remote frontier exchange slices.
//     * Publish everything to the g_dram_* globals.
//     * Zero the inter-pod barrier state.
//     * Raise g_pods_ready=1 (or -1 on any allocation/verify failure).
//
//   Synchronize on g_pods_ready
//     * Pod-0 harts wait() for the init leader; other pods hartsleep().
//     * If init failed, everybody exits cleanly.
//
//   Phase 0b — Each pod tid 0: copy DRAM params into this pod's L2SP
//     * Populate all g_* L2SP globals.
//     * Allocate frontier and next_frontier bitmaps from the L2SP heap
//       starting at l2sp_end (8-byte aligned). Abort if L2SP would overflow.
//     * Non-tid-0 harts wait() for barrier.num_threads() to be set, then
//       everyone syncs on the intra-pod barrier.
//
//   Phase 1 — Lightweight frontier initialization
//     * Cache L2SP globals into function-local consts (the hot loop
//       below references these, reducing L2SP reads).
//     * Partition vertex and bitmap-word ranges across threads within pod.
//     * Clear both bitmap buffers (cheap — L2SP only, no DRAM traffic).
//     * Only the pod that owns the source vertex sets the source bit,
//       guarded by a barrier.sync([&]{...}) so exactly one hart does it.
//     * Inter-pod barrier (pod leaders only) ensures all pods are ready.
//
//   Phase 2 — Main BFS loop  [THE REGION OF INTEREST]
//     Wrapped by cycle() timestamps. One level per outer iteration:
//       Step 1: Expand frontier. Each thread walks its word range of
//               `local_frontier`; for each set bit, reads neighbors via
//               CSR, CASes dist[neighbor] from -1 to cur_level+1. On
//               success, figure out the neighbor's owning pod:
//                 – If local: atomic_or_i32 into local_next_frontier.
//                 – If remote: atomic_or_i32 into g_remote_frontier[target].
//               ph_stat_phase(1/0) brackets this step so summarize.py
//               attributes the memory traffic to "useful" work.
//       Step 2: Intra-pod barrier — all local threads finish expansion.
//       Step 3: Inter-pod barrier (leaders only) — all pods finish Step 1.
//       Step 4: Drain THIS pod's remote-frontier slice into local_next_
//               frontier, atomic-OR then posted-swap-zero back. Each
//               thread handles its own word range.
//       Step 5: Intra-pod barrier; last arrival clears g_any_work.
//       Step 6: Promote next_frontier → frontier, clear next_frontier,
//               track whether any bit was nonzero -> local_any.
//               OR into g_any_work.
//       Step 7: Pod leaders (tid 0) OR into g_global_any_work, inter-pod
//               barrier, pod 0 decides: if any work → advance g_global_
//               bfs_iters and clear g_global_any_work; else set g_global_
//               done=1. Second inter-pod barrier propagates the decision,
//               then copy to L2SP g_bfs_done.
//       Step 8: Intra-pod barrier propagates g_bfs_done; break if done.
//
//   Phase 3 — Parallel reduction
//     * Each thread reduces its vertex range into local_sum / local_cnt /
//       local_max (guarded by ph_stat_phase so the reduction traffic is
//       also counted as useful).
//     * Reduce into per-pod L2SP accumulators with atomics + CAS-max.
//     * Pod leaders fold per-pod totals into the DRAM g_global_* counters,
//       then inter-pod barrier to make the global values consistent.
//
//   Phase 4 — Results & optional verify (pod 0, tid 0 only)
//     * Print iteration count, BFS cycles, reached%, max/sum/avg dist.
//     * Sanity checks: dist[source]==0 and reached>=1.
//     * If DO_FULL_VERIFY, walk every edge and check triangle inequality
//       dist[u] <= dist[v]+1. Print up to 10 violations.
//     * Emit final PASS/FAIL line.
//     * free() DRAM allocations (remote_frontier, dist, file_buffer).
//     * Set g_global_sim_exit=1.
//
//   Exit propagation
//     * Non-pod-0 leaders wait for g_global_sim_exit, then set local
//       g_sim_exit. Pod 0 tid 0 sets its own g_sim_exit. Every remaining
//       hart spins on g_sim_exit and returns.
// -----------------------------------------------------------------------------
// ---------- Main ----------
extern "C" int main(int argc, char **argv)
{
    int vtx_per_thread = DEFAULT_VTX_PER_THREAD;
    int degree         = DEFAULT_DEGREE;
    int desired_threads = 1024;

    for (int i = 1; i < argc; ++i) {
        if (!strcmp(argv[i], "--V") && i + 1 < argc)
            vtx_per_thread = parse_i(argv[++i], vtx_per_thread);
        else if (!strcmp(argv[i], "--D") && i + 1 < argc)
            degree = parse_i(argv[++i], degree);
        else if (!strcmp(argv[i], "--T") && i + 1 < argc)
            desired_threads = parse_i(argv[++i], desired_threads);
        else if (!strcmp(argv[i], "--help")) {
            std::printf("Usage: %s --V <vtx/thread> --D <degree> --T <threads>\n",
                        argv[0]);
            return 0;
        }
    }

    // ---- Hardware topology ----
    const int hart_in_core   = myThreadId();
    const int core_in_pod    = myCoreId();
    const int pod_in_pxn     = myPodId();
    const int pxn_id         = myPXNId();
    const int harts_per_core = myCoreThreads();
    const int cores_per_pod  = numPodCores();
    const int pods_per_pxn   = numPXNPods();
    const int num_pods       = pods_per_pxn;

    const int total_harts_hw =
        numPXN() * pods_per_pxn * cores_per_pod * harts_per_core;

    // Local thread ID within this pod
    const int tid = core_in_pod * harts_per_core + hart_in_core;
    const int threads_per_pod = cores_per_pod * harts_per_core;

    int total_threads = desired_threads;
    if (total_threads > threads_per_pod) total_threads = threads_per_pod;

    // Park non-participating threads and non-pxn-0 threads
    if (pxn_id != 0) {
        while (g_global_sim_exit == 0) hartsleep(1000);
        return 0;
    }
    if (tid >= total_threads) {
        while (g_global_sim_exit == 0) hartsleep(1000);
        return 0;
    }

    // Vertex partitioning
    const int N_local = vtx_per_thread * total_threads;  // vertices per pod
    const int N_total = N_local * num_pods;               // total vertices
    const int bm_words_local = (N_local + 31) / 32;

    barrier_ref barrier(&g_barrier_data);

    // ================================================================
    // Phase 0a: Pod 0, tid 0 — bulk-load graph + pre-initialized dist[]
    // ================================================================
    if (pod_in_pxn == 0 && tid == 0) {
        const int64_t total_edges = (int64_t)N_total * degree;

        // Compute expected file size
        size_t file_size = 20
            + (size_t)(N_total + 1) * sizeof(int32_t)
            + (size_t)total_edges * sizeof(int32_t)
            + (size_t)N_total * sizeof(int32_t);

        g_dram_file_buffer = (char *)std::malloc(file_size);
        if (!g_dram_file_buffer) {
            std::printf("ERROR: malloc failed for file buffer (%lu bytes)\n",
                        (unsigned long)file_size);
            g_dram_N = 0;
            g_pods_ready = -1;
            goto pod0_init_done;
        }

        // Bulk load graph file (zero simulated cost)
        bulk_load("uniform_graph.bin", g_dram_file_buffer, file_size);

        // Parse header
        {
            int32_t *header = (int32_t *)g_dram_file_buffer;
            int hdr_N      = header[0];
            int hdr_E      = header[1];
            int hdr_source = header[4];

            if (hdr_N != N_total || hdr_E > (int)total_edges) {
                std::printf("ERROR: graph header mismatch: file(N=%d E=%d) != expected(N=%d E<=%lld)\n",
                            hdr_N, hdr_E, N_total, (long long)total_edges);
                std::free(g_dram_file_buffer);
                g_dram_file_buffer = nullptr;
                g_dram_N = 0;
                g_pods_ready = -1;
                goto pod0_init_done;
            }

            g_dram_source = hdr_source;
            g_dram_csr_offsets = (int32_t *)(g_dram_file_buffer + 20);
            g_dram_csr_edges   = (int32_t *)(g_dram_file_buffer + 20 + (size_t)(N_total + 1) * sizeof(int32_t));
        }

        // Allocate dist[] in DRAM and bulk-load pre-initialized content
        {
            size_t dist_bytes = (size_t)N_total * sizeof(int32_t);
            g_dram_dist = (int32_t *)std::malloc(dist_bytes);
            if (!g_dram_dist) {
                std::printf("ERROR: malloc failed for dist[]\n");
                std::free(g_dram_file_buffer);
                g_dram_file_buffer = nullptr;
                g_dram_N = 0;
                g_pods_ready = -1;
                goto pod0_init_done;
            }

            // Bulk load pre-initialized dist[] (all -1, source=0)
            bulk_load("bfs_dist_init.bin", g_dram_dist, dist_bytes);
        }

        // Allocate remote frontier exchange buffers in DRAM
        {
            size_t rf_size = (size_t)num_pods * bm_words_local * sizeof(int32_t);
            g_remote_frontier = (volatile int32_t *)std::malloc(rf_size);
            if (!g_remote_frontier) {
                std::printf("ERROR: malloc failed for remote frontier (%lu bytes)\n",
                            (unsigned long)rf_size);
                std::free(g_dram_dist);
                std::free(g_dram_file_buffer);
                g_dram_N = 0;
                g_pods_ready = -1;
                goto pod0_init_done;
            }
            // Zero the remote frontier buffers
            std::memset((void *)g_remote_frontier, 0, rf_size);
        }

        // Set DRAM shared parameters
        g_dram_N = N_total;
        g_dram_N_local = N_local;
        g_dram_degree = degree;
        g_dram_total_threads_per_pod = total_threads;
        g_dram_bm_words_local = bm_words_local;
        g_dram_num_pods = num_pods;
        g_global_done = 0;
        g_global_any_work = 0;
        g_global_bfs_iters = 0;
        g_global_sim_exit = 0;
        g_global_sum_dist = 0;
        g_global_reached = 0;
        g_global_max_dist = 0;

        // Zero inter-pod barrier state
        g_inter_pod_count = 0;
        g_inter_pod_phase = 0;
        for (int p = 0; p < MAX_PODS; p++)
            g_pod_local_phase[p] = 0;

        std::printf("ROI-only multi-pod BFS: Phase 1 skipped (bulk-loaded dist[])\n");
        std::printf("Multi-pod CSR BFS: N=%d (%d per pod), %d pods, E=%d, degree=%d, source=%d\n",
                    N_total, N_local, num_pods, ((int32_t *)g_dram_file_buffer)[1], degree, g_dram_source);
        std::printf("HW: total_harts=%d, pxn=%d pods/pxn=%d cores/pod=%d harts/core=%d\n",
                    total_harts_hw, numPXN(), pods_per_pxn, cores_per_pod, harts_per_core);
        std::printf("Threads/pod=%d, bitmap_words/pod=%d\n", total_threads, bm_words_local);

        // Signal all pods that DRAM init is done
        g_pods_ready = 1;
    }

pod0_init_done:

    // All pod 0 threads wait for pod 0 tid 0 to finish init
    if (pod_in_pxn == 0) {
        while (g_pods_ready == 0) wait(100);
    }

    // Non-pod-0 threads: spin until pods_ready is set
    if (pod_in_pxn != 0) {
        while (g_pods_ready == 0) hartsleep(100);
    }

    // Check for init error
    if (g_pods_ready < 0 || g_dram_N == 0) {
        if (pod_in_pxn == 0 && tid == 0) g_global_sim_exit = 1;
        while (g_global_sim_exit == 0) hartsleep(100);
        return 1;
    }

    // ================================================================
    // Phase 0b: Each pod tid 0 sets up L2SP from DRAM parameters
    // ================================================================
    if (tid == 0) {
        barrier.num_threads() = total_threads;

        g_N             = g_dram_N;
        g_N_local       = g_dram_N_local;
        g_vtx_offset    = pod_in_pxn * g_dram_N_local;
        g_degree        = g_dram_degree;
        g_total_threads = g_dram_total_threads_per_pod;
        g_bitmap_words  = g_dram_bm_words_local;
        g_pod_id        = pod_in_pxn;
        g_num_pods      = g_dram_num_pods;
        g_bfs_done      = 0;
        g_sim_exit      = 0;
        g_any_work      = 0;
        g_sum_dist      = 0;
        g_reached       = 0;
        g_max_dist      = 0;
        g_source        = g_dram_source;

        // Cache DRAM pointers in L2SP
        g_csr_offsets = g_dram_csr_offsets;
        g_csr_edges   = g_dram_csr_edges;
        g_dist        = g_dram_dist;

        // Pointer to this pod's remote frontier exchange buffer
        g_my_remote_frontier = g_remote_frontier + (int64_t)pod_in_pxn * g_dram_bm_words_local;

        // Allocate frontier bitmaps from L2SP heap
        uintptr_t heap = ((uintptr_t)l2sp_end + 7) & ~(uintptr_t)7;
        g_frontier      = (volatile int32_t *)heap;
        heap += (size_t)bm_words_local * sizeof(int32_t);
        heap = (heap + 7) & ~(uintptr_t)7;
        g_next_frontier = (volatile int32_t *)heap;
        heap += (size_t)bm_words_local * sizeof(int32_t);
        heap = (heap + 7) & ~(uintptr_t)7;

        uintptr_t l2sp_base = 0x20000000;
        uintptr_t l2sp_cap  = podL2SPSize();
        size_t l2sp_used    = heap - l2sp_base;

        if (l2sp_used > l2sp_cap) {
            std::printf("ERROR: Pod %d L2SP overflow: need %lu bytes, have %lu\n",
                        pod_in_pxn, (unsigned long)l2sp_used, (unsigned long)l2sp_cap);
            g_N_local = 0;
        }
    }

    // Wait for tid 0 to set up L2SP
    while (barrier.num_threads() == 0) wait(10);

    barrier.sync();

    if (g_N_local == 0) {
        if (tid == 0) g_global_sim_exit = 1;
        while (g_global_sim_exit == 0) hartsleep(100);
        return 1;
    }

    // ================================================================
    // Phase 1: Lightweight frontier init only (dist[] was bulk-loaded)
    // ================================================================
    const int N_total_val  = g_N;
    const int N_local_val  = g_N_local;
    const int vtx_off      = g_vtx_offset;
    const int bm_words     = g_bitmap_words;
    const int source       = g_source;
    const int my_pod       = g_pod_id;
    const int npods        = g_num_pods;

    // Cache pointers locally
    int32_t *const local_offsets = g_csr_offsets;
    int32_t *const local_edges   = g_csr_edges;
    int32_t *const local_dist    = g_dist;
    volatile int32_t *const local_frontier      = g_frontier;
    volatile int32_t *const local_next_frontier = g_next_frontier;
    volatile int32_t *const local_my_remote     = g_my_remote_frontier;

    // Work distribution within pod
    const int vtx_per_thr = (N_local_val + total_threads - 1) / total_threads;
    const int v_lo_local = tid * vtx_per_thr;
    const int v_hi_local = std::min(v_lo_local + vtx_per_thr, N_local_val);

    // Bitmap word distribution within pod
    const int words_per_thread = (bm_words + total_threads - 1) / total_threads;
    const int w_lo = tid * words_per_thread;
    const int w_hi = std::min(w_lo + words_per_thread, bm_words);

    // Init frontier bitmaps in L2SP (cheap, no DRAM traffic)
    for (int w = w_lo; w < w_hi; ++w) {
        local_frontier[w]      = 0;
        local_next_frontier[w] = 0;
    }

    barrier.sync();

    // Set BFS source (only the pod that owns the source vertex)
    int source_pod = source / N_local_val;
    barrier.sync([&]() {
        if (my_pod == source_pod) {
            int source_local = source - vtx_off;
            local_frontier[source_local / 32] = 1 << (source_local % 32);
        }
    });

    // Inter-pod barrier: ensure all pods have initialized frontiers
    if (tid == 0) {
        inter_pod_barrier(my_pod, npods);
    }
    barrier.sync();

    if (my_pod == 0 && tid == 0)
        std::printf("BFS from source %d (pod %d)\n", source, source_pod);

    // ================================================================
    // Phase 2: Main BFS loop (level-synchronous, multi-pod) — THE ROI
    // ================================================================
    uint64_t t_bfs_start = cycle();

    while (true) {
        int cur_level = g_global_bfs_iters;

        // ---- Step 1: Expand frontier (parallel within pod) ----
        ph_stat_phase(1);

        for (int w = w_lo; w < w_hi; ++w) {
            int32_t word = local_frontier[w];
            if (word == 0) continue;

            while (word != 0) {
                int bit = __builtin_ctz(word);
                word &= word - 1;

                int vl = w * 32 + bit;  // local vertex index
                if (vl >= N_local_val) break;

                int v = vtx_off + vl;   // global vertex index
                int edge_begin = local_offsets[v];
                int edge_end   = local_offsets[v + 1];

                for (int ei = edge_begin; ei < edge_end; ++ei) {
                    int u = local_edges[ei];  // global neighbor

                    // Atomic CAS on dist[] in DRAM (works cross-pod)
                    if (atomic_compare_and_swap_i32(&local_dist[u], -1, cur_level + 1) == -1) {
                        // Determine which pod owns u
                        int target_pod = u / N_local_val;
                        int u_local = u - target_pod * N_local_val;
                        int wi = u_local / 32;
                        int32_t mask = 1 << (u_local % 32);

                        if (target_pod == my_pod) {
                            // Local: atomic OR into L2SP next_frontier
                            atomic_or_i32(&local_next_frontier[wi], mask);
                        } else {
                            // Remote: blocking atomic OR into DRAM exchange buffer
                            volatile int32_t *target_buf =
                                g_remote_frontier + (int64_t)target_pod * bm_words + wi;
                            atomic_or_i32(target_buf, mask);
                        }
                    }
                }
            }
        }

        ph_stat_phase(0);

        // ---- Step 2: Intra-pod barrier ----
        barrier.sync();

        // ---- Step 3: Inter-pod barrier (pod leader only) ----
        if (tid == 0) {
            inter_pod_barrier(my_pod, npods);
        }
        barrier.sync();

        // ---- Step 4: Merge remote frontier into L2SP next_frontier ----
        for (int w = w_lo; w < w_hi; ++w) {
            int32_t remote_word = local_my_remote[w];
            if (remote_word != 0) {
                atomic_or_i32(&local_next_frontier[w], remote_word);
                // Clear via posted atomic so MemController backing store stays in sync
                atomic_swap_i32_posted(&local_my_remote[w], 0);
            }
        }

        // ---- Step 5: Intra-pod barrier ----
        barrier.sync([&]() { g_any_work = 0; });

        // ---- Step 6: Swap frontiers, check local work ----
        int local_any = 0;
        for (int w = w_lo; w < w_hi; ++w) {
            int32_t val = local_next_frontier[w];
            local_frontier[w] = val;
            if (val) local_any = 1;
            local_next_frontier[w] = 0;
        }

        if (local_any) {
            atomic_or_i32(&g_any_work, 1);
        }

        barrier.sync();

        // ---- Step 7: Pod leaders coordinate global done via DRAM ----
        if (tid == 0) {
            // Report this pod's work status to global
            if (g_any_work) {
                atomic_or_i32(&g_global_any_work, 1);
            }

            // Inter-pod barrier
            inter_pod_barrier(my_pod, npods);

            // Pod 0 checks global done and advances iteration
            if (my_pod == 0) {
                if (g_global_any_work) {
                    g_global_bfs_iters++;
                    atomic_swap_i32_posted(&g_global_any_work, 0);
                } else {
                    g_global_done = 1;
                }
            }

            // Inter-pod barrier to propagate decision
            inter_pod_barrier(my_pod, npods);

            // Copy global done to local L2SP
            g_bfs_done = g_global_done;
        }

        // ---- Step 8: Intra-pod barrier to propagate done ----
        barrier.sync();

        if (g_bfs_done) break;
    }

    uint64_t t_bfs_end = cycle();

    // ================================================================
    // Phase 3: Parallel reduction for statistics
    // ================================================================
    ph_stat_phase(1);

    int64_t local_sum  = 0;
    int32_t local_cnt  = 0;
    int32_t local_max  = 0;

    // Each pod reduces its own partition
    for (int vl = v_lo_local; vl < v_hi_local; ++vl) {
        int d = local_dist[vtx_off + vl];
        if (d >= 0) {
            local_cnt++;
            local_sum += d;
            if (d > local_max) local_max = d;
        }
    }

    // Reduce within pod (L2SP atomics)
    atomic_fetch_add_i64(&g_sum_dist, local_sum);
    atomic_fetch_add_i32(&g_reached, local_cnt);

    int32_t old_max = g_max_dist;
    while (local_max > old_max) {
        int32_t prev = atomic_compare_and_swap_i32(&g_max_dist, old_max, local_max);
        if (prev == old_max) break;
        old_max = prev;
    }

    ph_stat_phase(0);
    barrier.sync();

    // Pod leader: reduce across pods via DRAM
    if (tid == 0) {
        atomic_fetch_add_i64(&g_global_sum_dist, g_sum_dist);
        atomic_fetch_add_i32(&g_global_reached, (int32_t)g_reached);

        int32_t pod_max = g_max_dist;
        int32_t old_gmax = g_global_max_dist;
        while (pod_max > old_gmax) {
            int32_t prev = atomic_compare_and_swap_i32(&g_global_max_dist, old_gmax, pod_max);
            if (prev == old_gmax) break;
            old_gmax = prev;
        }

        inter_pod_barrier(my_pod, npods);
    }
    barrier.sync();

    // ================================================================
    // Phase 4: Print results and optional verification (pod 0, tid 0)
    // ================================================================
    if (my_pod == 0 && tid == 0) {
        uint64_t bfs_cycles = t_bfs_end - t_bfs_start;

        std::printf("BFS done in %d iterations (%llu cycles)\n",
                    g_global_bfs_iters, (unsigned long long)bfs_cycles);
        int pct = g_global_reached > 0 ? (int)(100LL * g_global_reached / N_total_val) : 0;
        std::printf("Reached: %d/%d (%d%%)\n", (int)g_global_reached, N_total_val, pct);
        long long avg_x10 = g_global_reached > 0 ? (10LL * g_global_sum_dist / g_global_reached) : 0;
        std::printf("max_dist=%d  sum_dist=%lld  avg_dist=%lld.%lld\n",
                    (int)g_global_max_dist, (long long)g_global_sum_dist,
                    avg_x10 / 10, avg_x10 % 10);

        // Basic sanity checks
        bool ok = true;
        if (local_dist[source] != 0) {
            std::printf("FAIL: dist[%d]=%d (expected 0)\n", source, local_dist[source]);
            ok = false;
        }
        if (g_global_reached < 1) {
            std::printf("FAIL: reached=%d (expected >= 1)\n", (int)g_global_reached);
            ok = false;
        }

        // Full verification: triangle inequality on every edge
        if (DO_FULL_VERIFY) {
            std::printf("Running full verification (triangle inequality)...\n");
            int violations = 0;
            for (int v = 0; v < N_total_val; ++v) {
                int dv = local_dist[v];
                if (dv < 0) continue;
                int eb = local_offsets[v];
                int ee = local_offsets[v + 1];
                for (int ei = eb; ei < ee; ++ei) {
                    int u  = local_edges[ei];
                    int du = local_dist[u];
                    if (du < 0) continue;
                    if (du > dv + 1) {
                        if (violations < 10)
                            std::printf("  VIOLATION: dist[%d]=%d > dist[%d]+1=%d\n",
                                        u, du, v, dv + 1);
                        violations++;
                    }
                }
            }
            if (violations == 0)
                std::printf("Verification: PASS (all edges satisfy triangle inequality)\n");
            else
                std::printf("Verification: FAIL (%d violations)\n", violations);
            ok = ok && (violations == 0);
        }

        std::printf(ok ? "RESULT: PASS\n" : "RESULT: FAIL\n");

        std::printf("BFS complete, signaling exit.\n");
        std::fflush(stdout);

        std::free((void *)g_remote_frontier);
        std::free(g_dram_dist);
        std::free(g_dram_file_buffer);

        g_global_sim_exit = 1;
    }

    // All threads: propagate exit
    if (tid == 0 && my_pod != 0) {
        while (g_global_sim_exit == 0) hartsleep(100);
        g_sim_exit = 1;
    }
    if (my_pod == 0 && tid == 0) {
        g_sim_exit = 1;
    }

    while (g_sim_exit == 0) hartsleep(100);
    return 0;
}
