// pr_csr_weak_roi.cpp
// ROI-only CSR graph PageRank: skips parallel init by bulk-loading
// pre-generated rank[] and contrib[] arrays. Only simulates the iterative
// pull-based PageRank computation.
//
// Pre-initialized files (generated by gen_pr_init_state.py):
//   pr_rank_init.bin    - rank[] array (N int32, each = RANK_SCALE/N)
//   pr_contrib_init.bin - contrib[] array (N int32, each = rank[v]/degree[v])
//
// Memory layout:
//   DRAM  – file buffer (CSR offsets+edges+degree), rank[], contrib[]
//   L2SP  – barrier, control variables, DRAM pointers, degree pointer

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <algorithm>

#include <pandohammer/cpuinfo.h>
#include <pandohammer/atomic.h>
#include <pandohammer/hartsleep.h>
#include <pandohammer/mmio.h>
#include <pandohammer/staticdecl.h>

// ---------- Configuration defaults ----------
#ifndef DEFAULT_VTX_PER_THREAD
#define DEFAULT_VTX_PER_THREAD 1024
#endif

#ifndef DEFAULT_DEGREE
#define DEFAULT_DEGREE 16
#endif

#ifndef DEFAULT_ITERATIONS
#define DEFAULT_ITERATIONS 20
#endif

// ---------- Fixed-point PageRank constants ----------
static constexpr int64_t RANK_SCALE  = 1000000LL;
static constexpr int64_t DAMPING_NUM = 85;   // d = 0.85
static constexpr int64_t DAMPING_DEN = 100;

// ---------- Section attribute ----------
#define __l2sp__ __attribute__((section(".l2sp")))

// ---------- Blocking atomic OR (standard RISC-V amoor.w) ----------
static inline int32_t atomic_or_i32(volatile int32_t *ptr, int32_t val)
{
    int32_t ret;
    asm volatile("amoor.w %0, %2, 0(%1)"
                 : "=r"(ret) : "r"(ptr), "r"(val) : "memory");
    return ret;
}

// ---------- Helpers ----------
static int parse_i(const char *s, int d)
{
    if (!s) return d;
    char *e = nullptr;
    long v = strtol(s, &e, 10);
    return (e && *e == 0) ? (int)v : d;
}

static inline void wait(volatile int x)
{
    for (int i = 0; i < x; i++)
        asm volatile("nop");
}

// ---------- Bulk load helper ----------
static void bulk_load(const char *name, void *dest, size_t size)
{
    char fname_buf[64];
    int fi = 0;
    while (name[fi] && fi < 63) { fname_buf[fi] = name[fi]; fi++; }
    fname_buf[fi] = '\0';

    struct ph_bulk_load_desc desc;
    desc.filename_addr = (long)fname_buf;
    desc.dest_addr     = (long)dest;
    desc.size          = (long)size;
    desc.result        = 0;
    ph_bulk_load_file(&desc);

    if (desc.result <= 0) {
        std::printf("ERROR: bulk load '%s' failed (result=%ld)\n", name, desc.result);
    }
}

// ---------- Barrier (L2SP) ----------
struct barrier_data {
    int count;
    int signal;
    int num_threads;
};

__l2sp__ barrier_data g_barrier_data = {0, 0, 0};

class barrier_ref {
public:
    barrier_ref(barrier_data *ptr) : ptr_(ptr) {}
    barrier_data *ptr_;

    int &count()       { return ptr_->count; }
    int &signal()      { return ptr_->signal; }
    int &num_threads() { return ptr_->num_threads; }

    void sync() { sync([](){}); }

    template <typename F>
    void sync(F f) {
        int signal_ = signal();
        int count_  = atomic_fetch_add_i32(&count(), 1);
        if (count_ == num_threads() - 1) {
            count() = 0;
            f();
            signal() = !signal_;
        } else {
            static constexpr int backoff_limit = 1000;
            int backoff_counter = 8;
            while (signal() == signal_) {
                wait(backoff_counter);
                backoff_counter = std::min(backoff_counter * 2, backoff_limit);
            }
        }
    }
};

// ---------- L2SP globals ----------

// Graph parameters
__l2sp__ int32_t g_N;
__l2sp__ int32_t g_degree;
__l2sp__ int32_t g_total_threads;
__l2sp__ int32_t g_max_iters;

// Control
__l2sp__ volatile int g_sim_exit;

// Reduction accumulators
__l2sp__ volatile int64_t g_sum_rank;
__l2sp__ volatile int32_t g_max_rank;

// DRAM array pointers (stored in L2SP for fast access by all harts)
__l2sp__ char    *g_file_buffer;
__l2sp__ int32_t *g_csr_offsets;       // [N+1]
__l2sp__ int32_t *g_csr_edges;         // [E]
__l2sp__ int32_t *g_degree_arr;        // [N] (points into g_file_buffer)
__l2sp__ int32_t *g_rank;              // [N] DRAM
__l2sp__ int32_t *g_contrib;           // [N] DRAM

// Linker symbol: first free byte in L2SP after static data
extern "C" char l2sp_end[];

// ---------- Main ----------
extern "C" int main(int argc, char **argv)
{
    int vtx_per_thread  = DEFAULT_VTX_PER_THREAD;
    int degree          = DEFAULT_DEGREE;
    int desired_threads = 1024;
    int max_iters       = DEFAULT_ITERATIONS;

    for (int i = 1; i < argc; ++i) {
        if (!strcmp(argv[i], "--V") && i + 1 < argc)
            vtx_per_thread = parse_i(argv[++i], vtx_per_thread);
        else if (!strcmp(argv[i], "--D") && i + 1 < argc)
            degree = parse_i(argv[++i], degree);
        else if (!strcmp(argv[i], "--T") && i + 1 < argc)
            desired_threads = parse_i(argv[++i], desired_threads);
        else if (!strcmp(argv[i], "--I") && i + 1 < argc)
            max_iters = parse_i(argv[++i], max_iters);
        else if (!strcmp(argv[i], "--help")) {
            std::printf("Usage: %s --V <vtx/thread> --D <degree> --T <threads> --I <iterations>\n",
                        argv[0]);
            return 0;
        }
    }

    // ---- Hardware topology ----
    const int hart_in_core   = myThreadId();
    const int core_in_pod    = myCoreId();
    const int pod_in_pxn     = myPodId();
    const int pxn_id         = myPXNId();
    const int harts_per_core = myCoreThreads();
    const int cores_per_pod  = numPodCores();
    const int pods_per_pxn   = numPXNPods();

    const int total_harts_hw =
        numPXN() * pods_per_pxn * cores_per_pod * harts_per_core;

    const int tid = core_in_pod * harts_per_core + hart_in_core;
    const int threads_per_pod = cores_per_pod * harts_per_core;

    int total_threads = desired_threads;
    if (total_threads > threads_per_pod) total_threads = threads_per_pod;

    // Park non-participating threads
    if (tid >= total_threads) {
        while (g_sim_exit == 0) hartsleep(1000);
        return 0;
    }

    // Only run on pod 0, pxn 0
    if (pxn_id != 0 || pod_in_pxn != 0) {
        while (g_sim_exit == 0) hartsleep(1000);
        return 0;
    }

    barrier_ref barrier(&g_barrier_data);

    if (tid == 0) barrier.num_threads() = total_threads;
    while (barrier.num_threads() == 0) wait(10);

    // ================================================================
    // Phase 0: Thread 0 bulk-loads graph + pre-initialized PR state
    // ================================================================
    ph_stat_phase(0);
    barrier.sync([&]() {
        const int N = vtx_per_thread * total_threads;
        const int64_t total_edges = (int64_t)N * degree;

        g_N             = N;
        g_degree        = degree;
        g_total_threads = total_threads;
        g_max_iters     = max_iters;
        g_sim_exit      = 0;
        g_sum_rank      = 0;
        g_max_rank      = 0;
        g_file_buffer   = nullptr;

        // Compute expected file size:
        //   header(20) + offsets((N+1)*4) + edges(E*4) + degree(N*4)
        size_t file_size = 20
            + (size_t)(N + 1) * sizeof(int32_t)
            + (size_t)total_edges * sizeof(int32_t)
            + (size_t)N * sizeof(int32_t);

        g_file_buffer = (char *)std::malloc(file_size);
        if (!g_file_buffer) {
            std::printf("ERROR: malloc failed for file buffer (%lu bytes)\n",
                        (unsigned long)file_size);
            g_N = 0;
            return;
        }

        bulk_load("uniform_graph.bin", g_file_buffer, file_size);

        // Parse header
        int32_t *header = (int32_t *)g_file_buffer;
        int hdr_N = header[0];
        int hdr_E = header[1];

        if (hdr_N != N || hdr_E > (int)total_edges) {
            std::printf("ERROR: graph header mismatch: file(N=%d E=%d) != expected(N=%d E<=%lld)\n",
                        hdr_N, hdr_E, N, (long long)total_edges);
            std::free(g_file_buffer);
            g_file_buffer = nullptr;
            g_N = 0;
            return;
        }

        // Point CSR arrays into the loaded buffer
        g_csr_offsets = (int32_t *)(g_file_buffer + 20);
        g_csr_edges   = (int32_t *)(g_file_buffer + 20 + (size_t)(N + 1) * sizeof(int32_t));
        g_degree_arr  = (int32_t *)(g_file_buffer + 20 + (size_t)(N + 1) * sizeof(int32_t)
                                    + (size_t)total_edges * sizeof(int32_t));

        // Allocate rank[] and contrib[] in DRAM
        size_t arr_bytes = (size_t)N * sizeof(int32_t);
        g_rank = (int32_t *)std::malloc(arr_bytes);
        g_contrib = (int32_t *)std::malloc(arr_bytes);
        if (!g_rank || !g_contrib) {
            std::printf("ERROR: malloc failed for rank/contrib (%lu bytes each)\n",
                        (unsigned long)arr_bytes);
            std::free(g_file_buffer);
            g_file_buffer = nullptr;
            g_N = 0;
            return;
        }

        // Bulk load pre-initialized rank[] and contrib[]
        bulk_load("pr_rank_init.bin", g_rank, arr_bytes);
        bulk_load("pr_contrib_init.bin", g_contrib, arr_bytes);

        std::printf("ROI-only PageRank: Phase 1 skipped (bulk-loaded init state)\n");
        std::printf("rank[]/contrib[]: DRAM (%lu bytes each)\n", (unsigned long)arr_bytes);
        std::printf("CSR PageRank (bulk load): N=%d E=%d degree=%d iters=%d\n",
                    N, hdr_E, degree, max_iters);
        std::printf("HW: total_harts=%d, pxn=%d pods/pxn=%d cores/pod=%d harts/core=%d\n",
                    total_harts_hw, numPXN(), pods_per_pxn, cores_per_pod, harts_per_core);
        std::printf("Using total_threads=%d (within single pod for L2SP)\n", total_threads);
    });

    if (g_N == 0) {
        if (tid == 0) g_sim_exit = 1;
        while (g_sim_exit == 0) hartsleep(100);
        return 1;
    }

    const int N         = g_N;
    const int iters     = g_max_iters;

    // Work distribution
    const int vtx_per_thr = (N + total_threads - 1) / total_threads;
    const int v_lo = tid * vtx_per_thr;
    const int v_hi = std::min(v_lo + vtx_per_thr, N);

    // Cache DRAM pointers in local vars
    int32_t *const local_offsets  = g_csr_offsets;
    int32_t *const local_edges    = g_csr_edges;
    int32_t *const local_degree   = g_degree_arr;
    int32_t *const local_rank     = g_rank;
    int32_t *const local_contrib  = g_contrib;

    // base_rank = (1 - d) / N in fixed-point
    const int64_t base_rank = (RANK_SCALE * (DAMPING_DEN - DAMPING_NUM))
                              / (DAMPING_DEN * (int64_t)N);

    // ================================================================
    // Phase 1: SKIPPED — init state was bulk-loaded in Phase 0
    // ================================================================
    barrier.sync();

    if (tid == 0)
        std::printf("PageRank: %d iterations, N=%d\n", iters, N);

    // ================================================================
    // Phase 2: PageRank iterations — THE ROI
    // ================================================================
    uint64_t t_pr_start = cycle();

    for (int iter = 0; iter < iters; ++iter) {
        // ---- Compute new ranks (pull-based, each thread writes its own range) ----
        ph_stat_phase(1);

        for (int v = v_lo; v < v_hi; ++v) {
            int64_t sum = 0;
            int edge_begin = local_offsets[v];
            int edge_end   = local_offsets[v + 1];

            for (int ei = edge_begin; ei < edge_end; ++ei) {
                sum += local_contrib[local_edges[ei]];
            }

            local_rank[v] = (int32_t)(base_rank + (DAMPING_NUM * sum) / DAMPING_DEN);
        }

        ph_stat_phase(0);

        // Barrier: wait for all threads to finish rank computation
        barrier.sync();

        // ---- Update contrib[] for next iteration ----
        for (int v = v_lo; v < v_hi; ++v) {
            int d = local_degree[v];
            if (d > 0)
                local_contrib[v] = local_rank[v] / d;
            else
                local_contrib[v] = 0;
        }

        // Barrier: wait for all threads to finish contrib update
        barrier.sync();
    }

    uint64_t t_pr_end = cycle();

    // ================================================================
    // Phase 3: Parallel reduction for statistics
    // ================================================================
    ph_stat_phase(1);

    int64_t local_sum  = 0;
    int32_t local_max  = 0;

    for (int v = v_lo; v < v_hi; ++v) {
        int32_t r = local_rank[v];
        local_sum += r;
        if (r > local_max) local_max = r;
    }

    atomic_fetch_add_i64(&g_sum_rank, local_sum);

    // Atomic max via CAS loop
    int32_t old_max = g_max_rank;
    while (local_max > old_max) {
        int32_t prev = atomic_compare_and_swap_i32(&g_max_rank, old_max, local_max);
        if (prev == old_max) break;
        old_max = prev;
    }

    ph_stat_phase(0);
    barrier.sync();

    // ================================================================
    // Phase 4: Print results and verification (thread 0)
    // ================================================================
    if (tid == 0) {
        uint64_t pr_cycles = t_pr_end - t_pr_start;

        std::printf("PageRank done in %d iterations (%llu cycles)\n",
                    iters, (unsigned long long)pr_cycles);
        std::printf("sum_rank=%lld (expected ~%lld)  max_rank=%d\n",
                    (long long)g_sum_rank, (long long)RANK_SCALE, (int)g_max_rank);

        // Verification: rank sum should be close to RANK_SCALE
        bool ok = true;
        int64_t rank_diff = g_sum_rank - RANK_SCALE;
        if (rank_diff < 0) rank_diff = -rank_diff;

        // Tolerance: 1% of RANK_SCALE
        int64_t tolerance = RANK_SCALE / 100;
        if (rank_diff > tolerance) {
            std::printf("FAIL: |sum_rank - RANK_SCALE| = %lld > tolerance %lld\n",
                        (long long)rank_diff, (long long)tolerance);
            ok = false;
        } else {
            std::printf("Rank sum within tolerance (diff=%lld, tol=%lld)\n",
                        (long long)rank_diff, (long long)tolerance);
        }

        // Print top-5 ranks
        std::printf("Top-5 ranks:\n");
        for (int k = 0; k < 5 && k < N; ++k) {
            int32_t best_rank = -1;
            int best_v = -1;
            for (int v = 0; v < N; ++v) {
                if (local_rank[v] > best_rank) {
                    // Check not already printed
                    bool already = false;
                    // Simple O(k*N) — fine for k=5
                    best_rank = local_rank[v];
                    best_v = v;
                }
            }
            if (best_v >= 0) {
                std::printf("  rank[%d] = %d (%.4f)\n", best_v, best_rank,
                            (double)best_rank / RANK_SCALE);
                local_rank[best_v] = -1;  // mark as printed
            }
        }

        std::printf(ok ? "RESULT: PASS\n" : "RESULT: FAIL\n");

        std::printf("PageRank complete, signaling exit.\n");
        std::fflush(stdout);

        std::free(g_rank);
        std::free(g_contrib);
        std::free(g_file_buffer);

        g_sim_exit = 1;
    }

    while (g_sim_exit == 0) hartsleep(100);
    return 0;
}
