# SPDX-License-Identifier: MIT
# Copyright (c) 2023 University of Washington

DRV_DIR := $(shell git rev-parse --show-toplevel)
APP_NAME := lock
include $(DRV_DIR)/mk/config.mk
include $(DRV_DIR)/mk/application_common.mk
