
/* This file is automatically generated by the address map generator */
#ifndef __DRV_ADDRESS_MAP_H__
#define __DRV_ADDRESS_MAP_H__

/* Is absolute bit */
#define IS_ABSOLUTE_HI 63ul
#define IS_ABSOLUTE_LO 63ul

/* Absolute address bits */
#define ABSOLUTE_IS_DRAM_HI 62ul
#define ABSOLUTE_IS_DRAM_LO 62ul
#define ABSOLUTE_IS_L2SP_HI 61ul
#define ABSOLUTE_IS_L2SP_LO 61ul
#define ABSOLUTE_IS_CTRL_HI 29ul
#define ABSOLUTE_IS_CTRL_LO 29ul
#define ABSOLUTE_PXN_HI 60ul
#define ABSOLUTE_PXN_LO 61ul
#define ABSOLUTE_POD_HI 60ul
#define ABSOLUTE_POD_LO 61ul
#define ABSOLUTE_CORE_HI 60ul
#define ABSOLUTE_CORE_LO 59ul
#define ABSOLUTE_DRAM_OFFSET_HI 60ul
#define ABSOLUTE_DRAM_OFFSET_LO 0ul
#define ABSOLUTE_L2SP_OFFSET_HI 60ul
#define ABSOLUTE_L2SP_OFFSET_LO 0ul
#define ABSOLUTE_L1SP_OFFSET_HI 28ul
#define ABSOLUTE_L1SP_OFFSET_LO 0ul
#define ABSOLUTE_CTRL_OFFSET_HI 28ul
#define ABSOLUTE_CTRL_OFFSET_LO 0ul

/* Relative address bits */
#define RELATIVE_IS_DRAM_HI 30ul
#define RELATIVE_IS_DRAM_LO 30ul
#define RELATIVE_IS_L2SP_HI 29ul
#define RELATIVE_IS_L2SP_LO 29ul
#define RELATIVE_L1SP_OFFSET_HI 28ul
#define RELATIVE_L1SP_OFFSET_LO 0ul
#define RELATIVE_L2SP_OFFSET_HI 28ul
#define RELATIVE_L2SP_OFFSET_LO 0ul
#define RELATIVE_DRAM_OFFSET_HI 29ul
#define RELATIVE_DRAM_OFFSET_LO 0ul
#endif
        
